// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1205.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class R {
  static const String package = 'gogaming_app';

  static const String luckySpinBg = 'assets/audio/lucky_spin_bg.mp3';

  static const String piq = 'assets/html/piq.html';

  static const String accountInstructionsForUse = 'assets/images/account/Instructions_for_use.svg';

  static const String accountAccountActivity = 'assets/images/account/account_activity.png';

  static const String accountAndroidApkLogo = 'assets/images/account/android_apk_logo.svg';

  static const String accountAppleLogo = 'assets/images/account/apple_logo.svg';

  static const String accountBackupInstructionsIcon = 'assets/images/account/backup_instructions_icon.png';

  static const String accountBiometric = 'assets/images/account/biometric.png';

  static const String accountCopyIcon = 'assets/images/account/copy_icon.svg';

  static const String accountDeleteDevice = 'assets/images/account/delete_device.png';

  static const String accountDeviceManager = 'assets/images/account/device_manager.png';

  static const String accountDownloadDefalut = 'assets/images/account/download_defalut.png';

  static const String accountGoogleVerification = 'assets/images/account/google_verification.png';

  static const String accountIdentityVerification = 'assets/images/account/identity_verification.png';

  static const String accountModifyPassword = 'assets/images/account/modify_password.png';

  static const String accountModifyUserName = 'assets/images/account/modify_user_name.png';

  static const String accountPhoneVerification = 'assets/images/account/phone_verification.png';

  static const String accountWithdrawalWhitelist = 'assets/images/account/withdrawal_whitelist.png';

  static const String advancedCertificationDialog = 'assets/images/advanced_certification/dialog.png';

  static const String advancedCertificationVerifyType0 = 'assets/images/advanced_certification/verify_type_0.svg';

  static const String advancedCertificationVerifyType01 = 'assets/images/advanced_certification/verify_type_01.svg';

  static const String advancedCertificationVerifyType1 = 'assets/images/advanced_certification/verify_type_1.svg';

  static const String advancedCertificationVerifyType2 = 'assets/images/advanced_certification/verify_type_2.svg';

  static const String advancedCertificationVerifyType6 = 'assets/images/advanced_certification/verify_type_6.svg';

  static const String advancedCertificationVerifyType9 = 'assets/images/advanced_certification/verify_type_9.svg';

  static const String appbarAppbarArrowDown = 'assets/images/appbar/appbar_arrow_down.svg';

  static const String appbarAppbarWallet = 'assets/images/appbar/appbar_wallet.svg';

  static const String appbarAvatar = 'assets/images/appbar/avatar.png';

  static const String appbarSetting = 'assets/images/appbar/setting.svg';

  static const String appbarTempLogo = 'assets/images/appbar/temp_logo.svg';

  static const String appbarUnloginAvatar = 'assets/images/appbar/unlogin_avatar.png';

  static const String appealComplete = 'assets/images/appeal/complete.png';

  static const String appealPending = 'assets/images/appeal/pending.png';

  static const String appealSupplement = 'assets/images/appeal/supplement.png';

  static const String bankLogo000000 = 'assets/images/bank_logo/000-000.png';

  static const String bankLogo001001 = 'assets/images/bank_logo/001-001.png';

  static const String bankLogo001002 = 'assets/images/bank_logo/001-002.png';

  static const String bankLogo001003 = 'assets/images/bank_logo/001-003.png';

  static const String bankLogo001004 = 'assets/images/bank_logo/001-004.png';

  static const String bankLogo001005 = 'assets/images/bank_logo/001-005.png';

  static const String bankLogo001006 = 'assets/images/bank_logo/001-006.png';

  static const String bankLogo001007 = 'assets/images/bank_logo/001-007.png';

  static const String bankLogo001008 = 'assets/images/bank_logo/001-008.png';

  static const String bankLogo001009 = 'assets/images/bank_logo/001-009.png';

  static const String bankLogo001010 = 'assets/images/bank_logo/001-010.png';

  static const String bankLogo001011 = 'assets/images/bank_logo/001-011.png';

  static const String bankLogo001012 = 'assets/images/bank_logo/001-012.png';

  static const String bankLogo001013 = 'assets/images/bank_logo/001-013.png';

  static const String bankLogo001014 = 'assets/images/bank_logo/001-014.png';

  static const String bankLogo001015 = 'assets/images/bank_logo/001-015.png';

  static const String bankLogo001016 = 'assets/images/bank_logo/001-016.png';

  static const String bankLogo001017 = 'assets/images/bank_logo/001-017.png';

  static const String bankLogo001018 = 'assets/images/bank_logo/001-018.png';

  static const String bankLogo001019 = 'assets/images/bank_logo/001-019.png';

  static const String bankLogo001020 = 'assets/images/bank_logo/001-020.png';

  static const String bankLogo001022 = 'assets/images/bank_logo/001-022.png';

  static const String bankLogo001023 = 'assets/images/bank_logo/001-023.png';

  static const String bankLogo001025 = 'assets/images/bank_logo/001-025.png';

  static const String bankLogo001026 = 'assets/images/bank_logo/001-026.png';

  static const String bankLogo001027 = 'assets/images/bank_logo/001-027.png';

  static const String bankLogo001028 = 'assets/images/bank_logo/001-028.png';

  static const String bankLogo001029 = 'assets/images/bank_logo/001-029.png';

  static const String bankLogo001030 = 'assets/images/bank_logo/001-030.png';

  static const String bankLogo001031 = 'assets/images/bank_logo/001-031.png';

  static const String bankLogo001043 = 'assets/images/bank_logo/001-043.png';

  static const String bankLogo001044 = 'assets/images/bank_logo/001-044.png';

  static const String bankLogo001045 = 'assets/images/bank_logo/001-045.png';

  static const String bankLogo001057 = 'assets/images/bank_logo/001-057.png';

  static const String bankLogo001064 = 'assets/images/bank_logo/001-064.png';

  static const String bankLogo001065 = 'assets/images/bank_logo/001-065.png';

  static const String bankLogoABALID = 'assets/images/bank_logo/ABALID.png';

  static const String bankLogoABBANK = 'assets/images/bank_logo/ABBANK.png';

  static const String bankLogoABBKVN = 'assets/images/bank_logo/ABBKVN.png';

  static const String bankLogoABC = 'assets/images/bank_logo/ABC.png';

  static const String bankLogoACB = 'assets/images/bank_logo/ACB.png';

  static const String bankLogoAFF = 'assets/images/bank_logo/AFF.png';

  static const String bankLogoAGB = 'assets/images/bank_logo/AGB.png';

  static const String bankLogoAGOBMY = 'assets/images/bank_logo/AGOBMY.png';

  static const String bankLogoAGRIBANK = 'assets/images/bank_logo/AGRIBANK.png';

  static const String bankLogoAGSSID = 'assets/images/bank_logo/AGSSID.png';

  static const String bankLogoAGTBID = 'assets/images/bank_logo/AGTBID.png';

  static const String bankLogoALB = 'assets/images/bank_logo/ALB.png';

  static const String bankLogoALCBTH = 'assets/images/bank_logo/ALCBTH.png';

  static const String bankLogoALLAIN = 'assets/images/bank_logo/ALLAIN.png';

  static const String bankLogoAMB = 'assets/images/bank_logo/AMB.png';

  static const String bankLogoAMMBMY = 'assets/images/bank_logo/AMMBMY.png';

  static const String bankLogoANDBIN = 'assets/images/bank_logo/ANDBIN.png';

  static const String bankLogoANTDID = 'assets/images/bank_logo/ANTDID.png';

  static const String bankLogoANZ = 'assets/images/bank_logo/ANZ.png';

  static const String bankLogoANZBID = 'assets/images/bank_logo/ANZBID.png';

  static const String bankLogoANZBVN = 'assets/images/bank_logo/ANZBVN.png';

  static const String bankLogoARCU = 'assets/images/bank_logo/ARCU.png';

  static const String bankLogoARTGID = 'assets/images/bank_logo/ARTGID.png';

  static const String bankLogoASCB = 'assets/images/bank_logo/ASCB.png';

  static const String bankLogoASCBVN = 'assets/images/bank_logo/ASCBVN.png';

  static const String bankLogoAWANID = 'assets/images/bank_logo/AWANID.png';

  static const String bankLogoAXISIN = 'assets/images/bank_logo/AXISIN.png';

  static const String bankLogoAYCB = 'assets/images/bank_logo/AYCB.png';

  static const String bankLogoAYUDTH = 'assets/images/bank_logo/AYUDTH.png';

  static const String bankLogoBAAC = 'assets/images/bank_logo/BAAC.png';

  static const String bankLogoBANKWF = 'assets/images/bank_logo/BANKWF.png';

  static const String bankLogoBARBIN = 'assets/images/bank_logo/BARBIN.png';

  static const String bankLogoBAY = 'assets/images/bank_logo/BAY.png';

  static const String bankLogoBBAIID = 'assets/images/bank_logo/BBAIID.png';

  static const String bankLogoBBBAID = 'assets/images/bank_logo/BBBAID.png';

  static const String bankLogoBBIJID = 'assets/images/bank_logo/BBIJID.png';

  static const String bankLogoBBL = 'assets/images/bank_logo/BBL.png';

  static const String bankLogoBBUKID = 'assets/images/bank_logo/BBUKID.png';

  static const String bankLogoBCA = 'assets/images/bank_logo/BCA.png';

  static const String bankLogoBCIAID = 'assets/images/bank_logo/BCIAID.png';

  static const String bankLogoBDI = 'assets/images/bank_logo/BDI.png';

  static const String bankLogoBDINID = 'assets/images/bank_logo/BDINID.png';

  static const String bankLogoBDKIID = 'assets/images/bank_logo/BDKIID.png';

  static const String bankLogoBDO = 'assets/images/bank_logo/BDO.png';

  static const String bankLogoBDOe = 'assets/images/bank_logo/BDOe.png';

  static const String bankLogoBFTVVN = 'assets/images/bank_logo/BFTVVN.png';

  static const String bankLogoBGB = 'assets/images/bank_logo/BGB.png';

  static const String bankLogoBHB = 'assets/images/bank_logo/BHB.png';

  static const String bankLogoBICNID = 'assets/images/bank_logo/BICNID.png';

  static const String bankLogoBIDV = 'assets/images/bank_logo/BIDV.png';

  static const String bankLogoBIDVVN = 'assets/images/bank_logo/BIDVVN.png';

  static const String bankLogoBIDXID = 'assets/images/bank_logo/BIDXID.png';

  static const String bankLogoBIMB1 = 'assets/images/bank_logo/BIMB-1.png';

  static const String bankLogoBIMB = 'assets/images/bank_logo/BIMB.png';

  static const String bankLogoBJBANK = 'assets/images/bank_logo/BJBANK.png';

  static const String bankLogoBJRCB = 'assets/images/bank_logo/BJRCB.png';

  static const String bankLogoBJTMID = 'assets/images/bank_logo/BJTMID.png';

  static const String bankLogoBKCHTH = 'assets/images/bank_logo/BKCHTH.png';

  static const String bankLogoBKDNIN = 'assets/images/bank_logo/BKDNIN.png';

  static const String bankLogoBKIDID = 'assets/images/bank_logo/BKIDID.png';

  static const String bankLogoBKIDIN = 'assets/images/bank_logo/BKIDIN.png';

  static const String bankLogoBKKBTH = 'assets/images/bank_logo/BKKBTH.png';

  static const String bankLogoBKRMMY = 'assets/images/bank_logo/BKRMMY.png';

  static const String bankLogoBMDMID = 'assets/images/bank_logo/BMDMID.png';

  static const String bankLogoBMRIID = 'assets/images/bank_logo/BMRIID.png';

  static const String bankLogoBMSEID = 'assets/images/bank_logo/BMSEID.png';

  static const String bankLogoBMSIID = 'assets/images/bank_logo/BMSIID.png';

  static const String bankLogoBNDNIN = 'assets/images/bank_logo/BNDNIN.png';

  static const String bankLogoBNI = 'assets/images/bank_logo/BNI.png';

  static const String bankLogoBNIAID = 'assets/images/bank_logo/BNIAID.png';

  static const String bankLogoBNINID = 'assets/images/bank_logo/BNINID.png';

  static const String bankLogoBOA = 'assets/images/bank_logo/BOA.png';

  static const String bankLogoBOC = 'assets/images/bank_logo/BOC.png';

  static const String bankLogoBOCD = 'assets/images/bank_logo/BOCD.png';

  static const String bankLogoBOCY = 'assets/images/bank_logo/BOCY.png';

  static const String bankLogoBOD = 'assets/images/bank_logo/BOD.png';

  static const String bankLogoBODD = 'assets/images/bank_logo/BODD.png';

  static const String bankLogoBOHAIB = 'assets/images/bank_logo/BOHAIB.png';

  static const String bankLogoBOHN = 'assets/images/bank_logo/BOHN.png';

  static const String bankLogoBOJZ = 'assets/images/bank_logo/BOJZ.png';

  static const String bankLogoBOP = 'assets/images/bank_logo/BOP.png';

  static const String bankLogoBOQH = 'assets/images/bank_logo/BOQH.png';

  static const String bankLogoBOSZ = 'assets/images/bank_logo/BOSZ.png';

  static const String bankLogoBOTKID = 'assets/images/bank_logo/BOTKID.png';

  static const String bankLogoBOYK = 'assets/images/bank_logo/BOYK.png';

  static const String bankLogoBOZK = 'assets/images/bank_logo/BOZK.png';

  static const String bankLogoBPI = 'assets/images/bank_logo/BPI.png';

  static const String bankLogoBRI = 'assets/images/bank_logo/BRI.png';

  static const String bankLogoBRINID = 'assets/images/bank_logo/BRINID.png';

  static const String bankLogoBRISID = 'assets/images/bank_logo/BRISID.png';

  static const String bankLogoBSB = 'assets/images/bank_logo/BSB.png';

  static const String bankLogoBSMDID = 'assets/images/bank_logo/BSMDID.png';

  static const String bankLogoBSN = 'assets/images/bank_logo/BSN.png';

  static const String bankLogoBSNAMY = 'assets/images/bank_logo/BSNAMY.png';

  static const String bankLogoBTANID = 'assets/images/bank_logo/BTANID.png';

  static const String bankLogoBTPNID = 'assets/images/bank_logo/BTPNID.png';

  static const String bankLogoBUMIID = 'assets/images/bank_logo/BUMIID.png';

  static const String bankLogoBVB = 'assets/images/bank_logo/BVB.png';

  static const String bankLogoBVBVVN = 'assets/images/bank_logo/BVBVVN.png';

  static const String bankLogoBVICID = 'assets/images/bank_logo/BVICID.png';

  static const String bankLogoBWKIID = 'assets/images/bank_logo/BWKIID.png';

  static const String bankLogoBZMD = 'assets/images/bank_logo/BZMD.png';

  static const String bankLogoCAKE = 'assets/images/bank_logo/CAKE.png';

  static const String bankLogoCBBANK = 'assets/images/bank_logo/CBBANK.png';

  static const String bankLogoCBBQS = 'assets/images/bank_logo/CBBQS.png';

  static const String bankLogoCBININ = 'assets/images/bank_logo/CBININ.png';

  static const String bankLogoCBKF = 'assets/images/bank_logo/CBKF.png';

  static const String bankLogoCCB = 'assets/images/bank_logo/CCB.png';

  static const String bankLogoCCQTGB = 'assets/images/bank_logo/CCQTGB.png';

  static const String bankLogoCDB = 'assets/images/bank_logo/CDB.png';

  static const String bankLogoCDCB = 'assets/images/bank_logo/CDCB.png';

  static const String bankLogoCDRCB = 'assets/images/bank_logo/CDRCB.png';

  static const String bankLogoCEB = 'assets/images/bank_logo/CEB.png';

  static const String bankLogoCENAID = 'assets/images/bank_logo/CENAID.png';

  static const String bankLogoCGB = 'assets/images/bank_logo/CGB.png';

  static const String bankLogoCGNB = 'assets/images/bank_logo/CGNB.png';

  static const String bankLogoCIB = 'assets/images/bank_logo/CIB.png';

  static const String bankLogoCIBBMY = 'assets/images/bank_logo/CIBBMY.png';

  static const String bankLogoCIBBVN = 'assets/images/bank_logo/CIBBVN.png';

  static const String bankLogoCICTID = 'assets/images/bank_logo/CICTID.png';

  static const String bankLogoCIMB = 'assets/images/bank_logo/CIMB.png';

  static const String bankLogoCIMBN = 'assets/images/bank_logo/CIMBN.png';

  static const String bankLogoCIMBT = 'assets/images/bank_logo/CIMBT.png';

  static const String bankLogoCITI = 'assets/images/bank_logo/CITI.png';

  static const String bankLogoCITIC = 'assets/images/bank_logo/CITIC.png';

  static const String bankLogoCITIID = 'assets/images/bank_logo/CITIID.png';

  static const String bankLogoCITITH = 'assets/images/bank_logo/CITITH.png';

  static const String bankLogoCIUBIN = 'assets/images/bank_logo/CIUBIN.png';

  static const String bankLogoCMB = 'assets/images/bank_logo/CMB.png';

  static const String bankLogoCMBC = 'assets/images/bank_logo/CMBC.png';

  static const String bankLogoCNRBIN = 'assets/images/bank_logo/CNRBIN.png';

  static const String bankLogoCOMM = 'assets/images/bank_logo/COMM.png';

  static const String bankLogoCORPIN = 'assets/images/bank_logo/CORPIN.png';

  static const String bankLogoCQBANK = 'assets/images/bank_logo/CQBANK.png';

  static const String bankLogoCRBANK = 'assets/images/bank_logo/CRBANK.png';

  static const String bankLogoCRCBANK = 'assets/images/bank_logo/CRCBANK.png';

  static const String bankLogoCSCB = 'assets/images/bank_logo/CSCB.png';

  static const String bankLogoCSRCB = 'assets/images/bank_logo/CSRCB.png';

  static const String bankLogoCSYBIN = 'assets/images/bank_logo/CSYBIN.png';

  static const String bankLogoCTCBID = 'assets/images/bank_logo/CTCBID.png';

  static const String bankLogoCZBANK = 'assets/images/bank_logo/CZBANK.png';

  static const String bankLogoCZCB = 'assets/images/bank_logo/CZCB.png';

  static const String bankLogoCZRCB = 'assets/images/bank_logo/CZRCB.png';

  static const String bankLogoDAB = 'assets/images/bank_logo/DAB.png';

  static const String bankLogoDAIAVN = 'assets/images/bank_logo/DAIAVN.png';

  static const String bankLogoDAQINGB = 'assets/images/bank_logo/DAQINGB.png';

  static const String bankLogoDB = 'assets/images/bank_logo/DB.png';

  static const String bankLogoDBAGTH = 'assets/images/bank_logo/DBAGTH.png';

  static const String bankLogoDBS = 'assets/images/bank_logo/DBS.png';

  static const String bankLogoDBSBID = 'assets/images/bank_logo/DBSBID.png';

  static const String bankLogoDBSSIN = 'assets/images/bank_logo/DBSSIN.png';

  static const String bankLogoDCBLIN = 'assets/images/bank_logo/DCBLIN.png';

  static const String bankLogoDEUTIN = 'assets/images/bank_logo/DEUTIN.png';

  static const String bankLogoDEUTVN = 'assets/images/bank_logo/DEUTVN.png';

  static const String bankLogoDLB = 'assets/images/bank_logo/DLB.png';

  static const String bankLogoDLXBIN = 'assets/images/bank_logo/DLXBIN.png';

  static const String bankLogoDRCBCL = 'assets/images/bank_logo/DRCBCL.png';

  static const String bankLogoDYCB = 'assets/images/bank_logo/DYCB.png';

  static const String bankLogoDYCCB = 'assets/images/bank_logo/DYCCB.png';

  static const String bankLogoDZBANK = 'assets/images/bank_logo/DZBANK.png';

  static const String bankLogoDongABank = 'assets/images/bank_logo/DongABank.png';

  static const String bankLogoEACBVN = 'assets/images/bank_logo/EACBVN.png';

  static const String bankLogoEBVIVN = 'assets/images/bank_logo/EBVIVN.png';

  static const String bankLogoEGBANK = 'assets/images/bank_logo/EGBANK.png';

  static const String bankLogoEIB = 'assets/images/bank_logo/EIB.png';

  static const String bankLogoEKONID = 'assets/images/bank_logo/EKONID.png';

  static const String bankLogoEXIM = 'assets/images/bank_logo/EXIM.png';

  static const String bankLogoFDB = 'assets/images/bank_logo/FDB.png';

  static const String bankLogoFDRLIN = 'assets/images/bank_logo/FDRLIN.png';

  static const String bankLogoFJHXBC = 'assets/images/bank_logo/FJHXBC.png';

  static const String bankLogoFJNX = 'assets/images/bank_logo/FJNX.png';

  static const String bankLogoFOSHANBANK = 'assets/images/bank_logo/FOSHANBANK.png';

  static const String bankLogoFSCB = 'assets/images/bank_logo/FSCB.png';

  static const String bankLogoFXCB = 'assets/images/bank_logo/FXCB.png';

  static const String bankLogoGBNKVN = 'assets/images/bank_logo/GBNKVN.png';

  static const String bankLogoGCB = 'assets/images/bank_logo/GCB.png';

  static const String bankLogoGDB = 'assets/images/bank_logo/GDB.png';

  static const String bankLogoGDRCC = 'assets/images/bank_logo/GDRCC.png';

  static const String bankLogoGDRCU = 'assets/images/bank_logo/GDRCU.png';

  static const String bankLogoGHB = 'assets/images/bank_logo/GHB.png';

  static const String bankLogoGLBANK = 'assets/images/bank_logo/GLBANK.png';

  static const String bankLogoGNESID = 'assets/images/bank_logo/GNESID.png';

  static const String bankLogoGOHUTH = 'assets/images/bank_logo/GOHUTH.png';

  static const String bankLogoGPBank = 'assets/images/bank_logo/GPBank.png';

  static const String bankLogoGRCB = 'assets/images/bank_logo/GRCB.png';

  static const String bankLogoGSB = 'assets/images/bank_logo/GSB.png';

  static const String bankLogoGSBATH = 'assets/images/bank_logo/GSBATH.png';

  static const String bankLogoGSRCU = 'assets/images/bank_logo/GSRCU.png';

  static const String bankLogoGXRCU = 'assets/images/bank_logo/GXRCU.png';

  static const String bankLogoGYBANK = 'assets/images/bank_logo/GYBANK.png';

  static const String bankLogoGYCB = 'assets/images/bank_logo/GYCB.png';

  static const String bankLogoGZB = 'assets/images/bank_logo/GZB.png';

  static const String bankLogoGZRCU = 'assets/images/bank_logo/GZRCU.png';

  static const String bankLogoH3CB = 'assets/images/bank_logo/H3CB.png';

  static const String bankLogoHANABANK = 'assets/images/bank_logo/HANABANK.png';

  static const String bankLogoHBC = 'assets/images/bank_logo/HBC.png';

  static const String bankLogoHBHSBANK = 'assets/images/bank_logo/HBHSBANK.png';

  static const String bankLogoHBMBMY = 'assets/images/bank_logo/HBMBMY.png';

  static const String bankLogoHBRCU = 'assets/images/bank_logo/HBRCU.png';

  static const String bankLogoHBYCBANK = 'assets/images/bank_logo/HBYCBANK.png';

  static const String bankLogoHDB = 'assets/images/bank_logo/HDB.png';

  static const String bankLogoHDBANK = 'assets/images/bank_logo/HDBANK.png';

  static const String bankLogoHDBCVN = 'assets/images/bank_logo/HDBCVN.png';

  static const String bankLogoHDFCIN = 'assets/images/bank_logo/HDFCIN.png';

  static const String bankLogoHKB = 'assets/images/bank_logo/HKB.png';

  static const String bankLogoHKBEA = 'assets/images/bank_logo/HKBEA.png';

  static const String bankLogoHLB = 'assets/images/bank_logo/HLB.png';

  static const String bankLogoHLBBMY = 'assets/images/bank_logo/HLBBMY.png';

  static const String bankLogoHLBBVN = 'assets/images/bank_logo/HLBBVN.png';

  static const String bankLogoHNBNID = 'assets/images/bank_logo/HNBNID.png';

  static const String bankLogoHNRCC = 'assets/images/bank_logo/HNRCC.png';

  static const String bankLogoHNRCU = 'assets/images/bank_logo/HNRCU.png';

  static const String bankLogoHRBB = 'assets/images/bank_logo/HRBB.png';

  static const String bankLogoHRXJB = 'assets/images/bank_logo/HRXJB.png';

  static const String bankLogoHSBANK = 'assets/images/bank_logo/HSBANK.png';

  static const String bankLogoHSBC = 'assets/images/bank_logo/HSBC.png';

  static const String bankLogoHSBCID = 'assets/images/bank_logo/HSBCID.png';

  static const String bankLogoHSBCIN = 'assets/images/bank_logo/HSBCIN.png';

  static const String bankLogoHSBCTH = 'assets/images/bank_logo/HSBCTH.png';

  static const String bankLogoHSBCVN = 'assets/images/bank_logo/HSBCVN.png';

  static const String bankLogoHSBK = 'assets/images/bank_logo/HSBK.png';

  static const String bankLogoHURCB = 'assets/images/bank_logo/HURCB.png';

  static const String bankLogoHVBKID = 'assets/images/bank_logo/HVBKID.png';

  static const String bankLogoHVBKVN = 'assets/images/bank_logo/HVBKVN.png';

  static const String bankLogoHXBANK = 'assets/images/bank_logo/HXBANK.png';

  static const String bankLogoHZCB = 'assets/images/bank_logo/HZCB.png';

  static const String bankLogoHZCCB = 'assets/images/bank_logo/HZCCB.png';

  static const String bankLogoIABBVN = 'assets/images/bank_logo/IABBVN.png';

  static const String bankLogoIBKLIN = 'assets/images/bank_logo/IBKLIN.png';

  static const String bankLogoIBKOVN = 'assets/images/bank_logo/IBKOVN.png';

  static const String bankLogoICBC = 'assets/images/bank_logo/ICBC.png';

  static const String bankLogoICBKID = 'assets/images/bank_logo/ICBKID.png';

  static const String bankLogoICBKTH = 'assets/images/bank_logo/ICBKTH.png';

  static const String bankLogoICBVVN = 'assets/images/bank_logo/ICBVVN.png';

  static const String bankLogoICICIN = 'assets/images/bank_logo/ICICIN.png';

  static const String bankLogoIDFBIN = 'assets/images/bank_logo/IDFBIN.png';

  static const String bankLogoIDIBIN = 'assets/images/bank_logo/IDIBIN.png';

  static const String bankLogoIN0001 = 'assets/images/bank_logo/IN0001.png';

  static const String bankLogoIN0002 = 'assets/images/bank_logo/IN0002.png';

  static const String bankLogoIN0003 = 'assets/images/bank_logo/IN0003.png';

  static const String bankLogoIN0004 = 'assets/images/bank_logo/IN0004.png';

  static const String bankLogoIN0005 = 'assets/images/bank_logo/IN0005.png';

  static const String bankLogoIN0006 = 'assets/images/bank_logo/IN0006.png';

  static const String bankLogoIN0007 = 'assets/images/bank_logo/IN0007.png';

  static const String bankLogoIN0008 = 'assets/images/bank_logo/IN0008.png';

  static const String bankLogoIN0009 = 'assets/images/bank_logo/IN0009.png';

  static const String bankLogoIN0010 = 'assets/images/bank_logo/IN0010.png';

  static const String bankLogoIN0011 = 'assets/images/bank_logo/IN0011.png';

  static const String bankLogoIN0012 = 'assets/images/bank_logo/IN0012.png';

  static const String bankLogoIN0013 = 'assets/images/bank_logo/IN0013.png';

  static const String bankLogoIN0014 = 'assets/images/bank_logo/IN0014.png';

  static const String bankLogoIN0015 = 'assets/images/bank_logo/IN0015.png';

  static const String bankLogoIN0016 = 'assets/images/bank_logo/IN0016.png';

  static const String bankLogoIN0017 = 'assets/images/bank_logo/IN0017.png';

  static const String bankLogoIN0018 = 'assets/images/bank_logo/IN0018.png';

  static const String bankLogoIN0019 = 'assets/images/bank_logo/IN0019.png';

  static const String bankLogoIN0020 = 'assets/images/bank_logo/IN0020.png';

  static const String bankLogoIN0021 = 'assets/images/bank_logo/IN0021.png';

  static const String bankLogoIN0022 = 'assets/images/bank_logo/IN0022.png';

  static const String bankLogoIN0023 = 'assets/images/bank_logo/IN0023.png';

  static const String bankLogoIN0024 = 'assets/images/bank_logo/IN0024.png';

  static const String bankLogoIN0025 = 'assets/images/bank_logo/IN0025.png';

  static const String bankLogoIN0026 = 'assets/images/bank_logo/IN0026.png';

  static const String bankLogoIN0027 = 'assets/images/bank_logo/IN0027.png';

  static const String bankLogoIN0028 = 'assets/images/bank_logo/IN0028.png';

  static const String bankLogoIN0029 = 'assets/images/bank_logo/IN0029.png';

  static const String bankLogoIN0030 = 'assets/images/bank_logo/IN0030.png';

  static const String bankLogoIN0031 = 'assets/images/bank_logo/IN0031.png';

  static const String bankLogoIN0032 = 'assets/images/bank_logo/IN0032.png';

  static const String bankLogoIN0033 = 'assets/images/bank_logo/IN0033.png';

  static const String bankLogoIN0034 = 'assets/images/bank_logo/IN0034.png';

  static const String bankLogoIN0035 = 'assets/images/bank_logo/IN0035.png';

  static const String bankLogoIN0036 = 'assets/images/bank_logo/IN0036.png';

  static const String bankLogoIN0037 = 'assets/images/bank_logo/IN0037.png';

  static const String bankLogoINDBIN = 'assets/images/bank_logo/INDBIN.png';

  static const String bankLogoIOB = 'assets/images/bank_logo/IOB.png';

  static const String bankLogoIOBAIN = 'assets/images/bank_logo/IOBAIN.png';

  static const String bankLogoISBT = 'assets/images/bank_logo/ISBT.png';

  static const String bankLogoISBTTH = 'assets/images/bank_logo/ISBTTH.png';

  static const String bankLogoISTB = 'assets/images/bank_logo/ISTB.png';

  static const String bankLogoIVB = 'assets/images/bank_logo/IVB.png';

  static const String bankLogoJAJSID = 'assets/images/bank_logo/JAJSID.png';

  static const String bankLogoJAKAIN = 'assets/images/bank_logo/JAKAIN.png';

  static const String bankLogoJHBANK = 'assets/images/bank_logo/JHBANK.png';

  static const String bankLogoJINCHB = 'assets/images/bank_logo/JINCHB.png';

  static const String bankLogoJJBANK = 'assets/images/bank_logo/JJBANK.png';

  static const String bankLogoJLBANK = 'assets/images/bank_logo/JLBANK.png';

  static const String bankLogoJLRCU = 'assets/images/bank_logo/JLRCU.png';

  static const String bankLogoJNBANK = 'assets/images/bank_logo/JNBANK.png';

  static const String bankLogoJRCB = 'assets/images/bank_logo/JRCB.png';

  static const String bankLogoJSB = 'assets/images/bank_logo/JSB.png';

  static const String bankLogoJSBANK = 'assets/images/bank_logo/JSBANK.png';

  static const String bankLogoJSRCU = 'assets/images/bank_logo/JSRCU.png';

  static const String bankLogoJXBANK = 'assets/images/bank_logo/JXBANK.png';

  static const String bankLogoJXRCU = 'assets/images/bank_logo/JXRCU.png';

  static const String bankLogoJZBANK = 'assets/images/bank_logo/JZBANK.png';

  static const String bankLogoKARBIN = 'assets/images/bank_logo/KARBIN.png';

  static const String bankLogoKASITH = 'assets/images/bank_logo/KASITH.png';

  static const String bankLogoKBANK = 'assets/images/bank_logo/KBANK.png';

  static const String bankLogoKIENLONG = 'assets/images/bank_logo/KIENLONG.png';

  static const String bankLogoKK = 'assets/images/bank_logo/KK.png';

  static const String bankLogoKKBKIN = 'assets/images/bank_logo/KKBKIN.png';

  static const String bankLogoKKPBTH = 'assets/images/bank_logo/KKPBTH.png';

  static const String bankLogoKKR = 'assets/images/bank_logo/KKR.png';

  static const String bankLogoKLB = 'assets/images/bank_logo/KLB.png';

  static const String bankLogoKLBKVN = 'assets/images/bank_logo/KLBKVN.png';

  static const String bankLogoKNK = 'assets/images/bank_logo/KNK.png';

  static const String bankLogoKORLABANK = 'assets/images/bank_logo/KORLABANK.png';

  static const String bankLogoKRTHTH = 'assets/images/bank_logo/KRTHTH.png';

  static const String bankLogoKSRB = 'assets/images/bank_logo/KSRB.png';

  static const String bankLogoKTB = 'assets/images/bank_logo/KTB.png';

  static const String bankLogoKVBLIN = 'assets/images/bank_logo/KVBLIN.png';

  static const String bankLogoLAHRTH = 'assets/images/bank_logo/LAHRTH.png';

  static const String bankLogoLANGFB = 'assets/images/bank_logo/LANGFB.png';

  static const String bankLogoLAVBIN = 'assets/images/bank_logo/LAVBIN.png';

  static const String bankLogoLBP = 'assets/images/bank_logo/LBP.png';

  static const String bankLogoLHBANK = 'assets/images/bank_logo/LHBANK.png';

  static const String bankLogoLPB = 'assets/images/bank_logo/LPB.png';

  static const String bankLogoLSBANK = 'assets/images/bank_logo/LSBANK.png';

  static const String bankLogoLSBC = 'assets/images/bank_logo/LSBC.png';

  static const String bankLogoLSCCB = 'assets/images/bank_logo/LSCCB.png';

  static const String bankLogoLVBKVN = 'assets/images/bank_logo/LVBKVN.png';

  static const String bankLogoLYBANK = 'assets/images/bank_logo/LYBANK.png';

  static const String bankLogoLYCB = 'assets/images/bank_logo/LYCB.png';

  static const String bankLogoLZYH = 'assets/images/bank_logo/LZYH.png';

  static const String bankLogoMAHBIN = 'assets/images/bank_logo/MAHBIN.png';

  static const String bankLogoMASDID = 'assets/images/bank_logo/MASDID.png';

  static const String bankLogoMAYAID = 'assets/images/bank_logo/MAYAID.png';

  static const String bankLogoMAYOID = 'assets/images/bank_logo/MAYOID.png';

  static const String bankLogoMB = 'assets/images/bank_logo/MB.png';

  static const String bankLogoMBB = 'assets/images/bank_logo/MBB.png';

  static const String bankLogoMBBANK = 'assets/images/bank_logo/MBBANK.png';

  static const String bankLogoMBBEMY = 'assets/images/bank_logo/MBBEMY.png';

  static const String bankLogoMBBI = 'assets/images/bank_logo/MBBI.png';

  static const String bankLogoMCOBVN = 'assets/images/bank_logo/MCOBVN.png';

  static const String bankLogoMDR = 'assets/images/bank_logo/MDR.png';

  static const String bankLogoMEGAID = 'assets/images/bank_logo/MEGAID.png';

  static const String bankLogoMHBBVN = 'assets/images/bank_logo/MHBBVN.png';

  static const String bankLogoMHCB = 'assets/images/bank_logo/MHCB.png';

  static const String bankLogoMHCBTH = 'assets/images/bank_logo/MHCBTH.png';

  static const String bankLogoMSB = 'assets/images/bank_logo/MSB.png';

  static const String bankLogoMSCBVN = 'assets/images/bank_logo/MSCBVN.png';

  static const String bankLogoMTB = 'assets/images/bank_logo/MTB.png';

  static const String bankLogoMTBANK = 'assets/images/bank_logo/MTBANK.png';

  static const String bankLogoMTMB = 'assets/images/bank_logo/MTMB.png';

  static const String bankLogoMUABID = 'assets/images/bank_logo/MUABID.png';

  static const String bankLogoMYBANK = 'assets/images/bank_logo/MYBANK.png';

  static const String bankLogoNAMAVN = 'assets/images/bank_logo/NAMAVN.png';

  static const String bankLogoNASCVN = 'assets/images/bank_logo/NASCVN.png';

  static const String bankLogoNBBANK = 'assets/images/bank_logo/NBBANK.png';

  static const String bankLogoNBYZ = 'assets/images/bank_logo/NBYZ.png';

  static const String bankLogoNCB = 'assets/images/bank_logo/NCB.png';

  static const String bankLogoNHB = 'assets/images/bank_logo/NHB.png';

  static const String bankLogoNHQS = 'assets/images/bank_logo/NHQS.png';

  static const String bankLogoNISPID = 'assets/images/bank_logo/NISPID.png';

  static const String bankLogoNJCB = 'assets/images/bank_logo/NJCB.png';

  static const String bankLogoNOBUID = 'assets/images/bank_logo/NOBUID.png';

  static const String bankLogoNUPAID = 'assets/images/bank_logo/NUPAID.png';

  static const String bankLogoNVBAVN = 'assets/images/bank_logo/NVBAVN.png';

  static const String bankLogoNXBANK = 'assets/images/bank_logo/NXBANK.png';

  static const String bankLogoNXRCU = 'assets/images/bank_logo/NXRCU.png';

  static const String bankLogoNYNB = 'assets/images/bank_logo/NYNB.png';

  static const String bankLogoNamABank = 'assets/images/bank_logo/NamABank.png';

  static const String bankLogoOCB = 'assets/images/bank_logo/OCB.png';

  static const String bankLogoOCBC = 'assets/images/bank_logo/OCBC.png';

  static const String bankLogoOCBCMY = 'assets/images/bank_logo/OCBCMY.png';

  static const String bankLogoOJBAVN = 'assets/images/bank_logo/OJBAVN.png';

  static const String bankLogoORBANK = 'assets/images/bank_logo/ORBANK.png';

  static const String bankLogoORBCIN = 'assets/images/bank_logo/ORBCIN.png';

  static const String bankLogoORCOVN = 'assets/images/bank_logo/ORCOVN.png';

  static const String bankLogoOceanbank = 'assets/images/bank_logo/Oceanbank.png';

  static const String bankLogoPBB = 'assets/images/bank_logo/PBB.png';

  static const String bankLogoPBBEMY = 'assets/images/bank_logo/PBBEMY.png';

  static const String bankLogoPBVN = 'assets/images/bank_logo/PBVN.png';

  static const String bankLogoPDJGID = 'assets/images/bank_logo/PDJGID.png';

  static const String bankLogoPDRIID = 'assets/images/bank_logo/PDRIID.png';

  static const String bankLogoPDSBID = 'assets/images/bank_logo/PDSBID.png';

  static const String bankLogoPDSUID = 'assets/images/bank_logo/PDSUID.png';

  static const String bankLogoPGBLVN = 'assets/images/bank_logo/PGBLVN.png';

  static const String bankLogoPGBank = 'assets/images/bank_logo/PGBank.png';

  static const String bankLogoPNB = 'assets/images/bank_logo/PNB.png';

  static const String bankLogoPNBSID = 'assets/images/bank_logo/PNBSID.png';

  static const String bankLogoPPTP = 'assets/images/bank_logo/PPTP.png';

  static const String bankLogoPSBC = 'assets/images/bank_logo/PSBC.png';

  static const String bankLogoPSIBIN = 'assets/images/bank_logo/PSIBIN.png';

  static const String bankLogoPUNBIN1 = 'assets/images/bank_logo/PUNBIN-1.png';

  static const String bankLogoPUNBIN = 'assets/images/bank_logo/PUNBIN.png';

  static const String bankLogoPVCOMBANK = 'assets/images/bank_logo/PVCOMBANK.png';

  static const String bankLogoQDCCB = 'assets/images/bank_logo/QDCCB.png';

  static const String bankLogoQLBANK = 'assets/images/bank_logo/QLBANK.png';

  static const String bankLogoRABOID = 'assets/images/bank_logo/RABOID.png';

  static const String bankLogoRCBC = 'assets/images/bank_logo/RCBC.png';

  static const String bankLogoRHB = 'assets/images/bank_logo/RHB.png';

  static const String bankLogoRHBBMY = 'assets/images/bank_logo/RHBBMY.png';

  static const String bankLogoSACLVN = 'assets/images/bank_logo/SACLVN.png';

  static const String bankLogoSACOM = 'assets/images/bank_logo/SACOM.png';

  static const String bankLogoSBC = 'assets/images/bank_logo/SBC.png';

  static const String bankLogoSBIDID = 'assets/images/bank_logo/SBIDID.png';

  static const String bankLogoSBININ = 'assets/images/bank_logo/SBININ.png';

  static const String bankLogoSBITVN = 'assets/images/bank_logo/SBITVN.png';

  static const String bankLogoSBJKID = 'assets/images/bank_logo/SBJKID.png';

  static const String bankLogoSCB = 'assets/images/bank_logo/SCB.png';

  static const String bankLogoSCBLID = 'assets/images/bank_logo/SCBLID.png';

  static const String bankLogoSCBLTH = 'assets/images/bank_logo/SCBLTH.png';

  static const String bankLogoSCBLVN = 'assets/images/bank_logo/SCBLVN.png';

  static const String bankLogoSCCB = 'assets/images/bank_logo/SCCB.png';

  static const String bankLogoSCH = 'assets/images/bank_logo/SCH.png';

  static const String bankLogoSCMB = 'assets/images/bank_logo/SCMB.png';

  static const String bankLogoSCRCU = 'assets/images/bank_logo/SCRCU.png';

  static const String bankLogoSCTB = 'assets/images/bank_logo/SCTB.png';

  static const String bankLogoSDEB = 'assets/images/bank_logo/SDEB.png';

  static const String bankLogoSDRCU = 'assets/images/bank_logo/SDRCU.png';

  static const String bankLogoSEABANK = 'assets/images/bank_logo/SEABANK.png';

  static const String bankLogoSEAVVN = 'assets/images/bank_logo/SEAVVN.png';

  static const String bankLogoSFDB = 'assets/images/bank_logo/SFDB.png';

  static const String bankLogoSGTTVN = 'assets/images/bank_logo/SGTTVN.png';

  static const String bankLogoSHB = 'assets/images/bank_logo/SHB.png';

  static const String bankLogoSHBANK = 'assets/images/bank_logo/SHBANK.png';

  static const String bankLogoSHBAVN = 'assets/images/bank_logo/SHBAVN.png';

  static const String bankLogoSHRCB = 'assets/images/bank_logo/SHRCB.png';

  static const String bankLogoSICOTH = 'assets/images/bank_logo/SICOTH.png';

  static const String bankLogoSITYTH = 'assets/images/bank_logo/SITYTH.png';

  static const String bankLogoSJBANK = 'assets/images/bank_logo/SJBANK.png';

  static const String bankLogoSMBC = 'assets/images/bank_logo/SMBC.png';

  static const String bankLogoSMBCTH = 'assets/images/bank_logo/SMBCTH.png';

  static const String bankLogoSOININ = 'assets/images/bank_logo/SOININ.png';

  static const String bankLogoSPABANK = 'assets/images/bank_logo/SPABANK.png';

  static const String bankLogoSPDB = 'assets/images/bank_logo/SPDB.png';

  static const String bankLogoSRBANK = 'assets/images/bank_logo/SRBANK.png';

  static const String bankLogoSRCB = 'assets/images/bank_logo/SRCB.png';

  static const String bankLogoSRCC = 'assets/images/bank_logo/SRCC.png';

  static const String bankLogoSTB = 'assets/images/bank_logo/STB.png';

  static const String bankLogoSXCB = 'assets/images/bank_logo/SXCB.png';

  static const String bankLogoSXRCCU = 'assets/images/bank_logo/SXRCCU.png';

  static const String bankLogoSYNBIN = 'assets/images/bank_logo/SYNBIN.png';

  static const String bankLogoSZSBK = 'assets/images/bank_logo/SZSBK.png';

  static const String bankLogoSaigonbank = 'assets/images/bank_logo/Saigonbank.png';

  static const String bankLogoTACCB = 'assets/images/bank_logo/TACCB.png';

  static const String bankLogoTBANK = 'assets/images/bank_logo/TBANK.png';

  static const String bankLogoTCB = 'assets/images/bank_logo/TCB.png';

  static const String bankLogoTCCB = 'assets/images/bank_logo/TCCB.png';

  static const String bankLogoTCRBTH = 'assets/images/bank_logo/TCRBTH.png';

  static const String bankLogoTCRCB = 'assets/images/bank_logo/TCRCB.png';

  static const String bankLogoTFPCTH = 'assets/images/bank_logo/TFPCTH.png';

  static const String bankLogoTIBTTH = 'assets/images/bank_logo/TIBTTH.png';

  static const String bankLogoTICRB = 'assets/images/bank_logo/TICRB.png';

  static const String bankLogoTISCO = 'assets/images/bank_logo/TISCO.png';

  static const String bankLogoTMB = 'assets/images/bank_logo/TMB.png';

  static const String bankLogoTMBKTH = 'assets/images/bank_logo/TMBKTH.png';

  static const String bankLogoTMBLIN = 'assets/images/bank_logo/TMBLIN.png';

  static const String bankLogoTPB = 'assets/images/bank_logo/TPB.png';

  static const String bankLogoTPBVVN = 'assets/images/bank_logo/TPBVVN.png';

  static const String bankLogoTRCB = 'assets/images/bank_logo/TRCB.png';

  static const String bankLogoTZCB = 'assets/images/bank_logo/TZCB.png';

  static const String bankLogoUBININ = 'assets/images/bank_logo/UBININ.png';

  static const String bankLogoUBOBTH = 'assets/images/bank_logo/UBOBTH.png';

  static const String bankLogoUBP = 'assets/images/bank_logo/UBP.png';

  static const String bankLogoUCBAIN = 'assets/images/bank_logo/UCBAIN.png';

  static const String bankLogoUOB = 'assets/images/bank_logo/UOB.png';

  static const String bankLogoUOVBMY = 'assets/images/bank_logo/UOVBMY.png';

  static const String bankLogoUOVBTH = 'assets/images/bank_logo/UOVBTH.png';

  static const String bankLogoUOVBVN = 'assets/images/bank_logo/UOVBVN.png';

  static const String bankLogoURMQCCB = 'assets/images/bank_logo/URMQCCB.png';

  static const String bankLogoUTBIIN = 'assets/images/bank_logo/UTBIIN.png';

  static const String bankLogoVAB = 'assets/images/bank_logo/VAB.png';

  static const String bankLogoVBAAVN = 'assets/images/bank_logo/VBAAVN.png';

  static const String bankLogoVCB = 'assets/images/bank_logo/VCB.png';

  static const String bankLogoVCBCVN = 'assets/images/bank_logo/VCBCVN.png';

  static const String bankLogoVIB = 'assets/images/bank_logo/VIB.png';

  static const String bankLogoVIDPVN = 'assets/images/bank_logo/VIDPVN.png';

  static const String bankLogoVIETBANK = 'assets/images/bank_logo/VIETBANK.png';

  static const String bankLogoVIETCAPITAL = 'assets/images/bank_logo/VIETCAPITAL.png';

  static const String bankLogoVIJBIN = 'assets/images/bank_logo/VIJBIN.png';

  static const String bankLogoVNACVN = 'assets/images/bank_logo/VNACVN.png';

  static const String bankLogoVNIBVN = 'assets/images/bank_logo/VNIBVN.png';

  static const String bankLogoVPB = 'assets/images/bank_logo/VPB.png';

  static const String bankLogoVPBKVN = 'assets/images/bank_logo/VPBKVN.png';

  static const String bankLogoVRB = 'assets/images/bank_logo/VRB.png';

  static const String bankLogoVRBAVN = 'assets/images/bank_logo/VRBAVN.png';

  static const String bankLogoVTB = 'assets/images/bank_logo/VTB.png';

  static const String bankLogoVTCBVN = 'assets/images/bank_logo/VTCBVN.png';

  static const String bankLogoWBVNVN = 'assets/images/bank_logo/WBVNVN.png';

  static const String bankLogoWHCCB = 'assets/images/bank_logo/WHCCB.png';

  static const String bankLogoWHRCB = 'assets/images/bank_logo/WHRCB.png';

  static const String bankLogoWJRCB = 'assets/images/bank_logo/WJRCB.png';

  static const String bankLogoWOORI = 'assets/images/bank_logo/WOORI.png';

  static const String bankLogoWRCB = 'assets/images/bank_logo/WRCB.png';

  static const String bankLogoWZCB = 'assets/images/bank_logo/WZCB.png';

  static const String bankLogoXABANK = 'assets/images/bank_logo/XABANK.png';

  static const String bankLogoXCYH = 'assets/images/bank_logo/XCYH.png';

  static const String bankLogoXHBANK = 'assets/images/bank_logo/XHBANK.png';

  static const String bankLogoXLBANK = 'assets/images/bank_logo/XLBANK.png';

  static const String bankLogoXTB = 'assets/images/bank_logo/XTB.png';

  static const String bankLogoXXBANK = 'assets/images/bank_logo/XXBANK.png';

  static const String bankLogoXYBANK = 'assets/images/bank_logo/XYBANK.png';

  static const String bankLogoYBCCB = 'assets/images/bank_logo/YBCCB.png';

  static const String bankLogoYCCB = 'assets/images/bank_logo/YCCB.png';

  static const String bankLogoYDRCB = 'assets/images/bank_logo/YDRCB.png';

  static const String bankLogoYESBIN = 'assets/images/bank_logo/YESBIN.png';

  static const String bankLogoYNRCC = 'assets/images/bank_logo/YNRCC.png';

  static const String bankLogoYQCCB = 'assets/images/bank_logo/YQCCB.png';

  static const String bankLogoYXCCB = 'assets/images/bank_logo/YXCCB.png';

  static const String bankLogoZBCB = 'assets/images/bank_logo/ZBCB.png';

  static const String bankLogoZGCCB = 'assets/images/bank_logo/ZGCCB.png';

  static const String bankLogoZJKCCB = 'assets/images/bank_logo/ZJKCCB.png';

  static const String bankLogoZJNX = 'assets/images/bank_logo/ZJNX.png';

  static const String bankLogoZJTLCB = 'assets/images/bank_logo/ZJTLCB.png';

  static const String bankLogoZRCBANK = 'assets/images/bank_logo/ZRCBANK.png';

  static const String bankLogoZYCBANK = 'assets/images/bank_logo/ZYCBANK.png';

  static const String bankLogoZZBANK = 'assets/images/bank_logo/ZZBANK.png';

  static const String bankLogoIbank = 'assets/images/bank_logo/ibank.png';

  static const String bonusSelectedBorder = 'assets/images/bonus/selected_border.svg';

  static const String commonCheckBox = 'assets/images/common/check_box.png';

  static const String commonCheckRound = 'assets/images/common/check_round.png';

  static const String commonDailyContestRankBack = 'assets/images/common/daily_contest_rank_back.png';

  static const String commonDialogErrorBig = 'assets/images/common/dialog_error_big.png';

  static const String commonDialogIphone = 'assets/images/common/dialog_iphone.png';

  static const String commonDialogSuccessBig = 'assets/images/common/dialog_success_big.png';

  static const String commonDialogWait = 'assets/images/common/dialog_wait.png';

  static const String commonEmpty = 'assets/images/common/empty.png';

  static const String commonFilter = 'assets/images/common/filter.svg';

  static const String commonLightIcon = 'assets/images/common/light_icon.png';

  static const String commonMaintaining = 'assets/images/common/maintaining.png';

  static const String commonRoundBack = 'assets/images/common/round_back.png';

  static const String commonStatement = 'assets/images/common/statement.png';

  static const String commonToastError = 'assets/images/common/toast_error.png';

  static const String commonToastSuccess = 'assets/images/common/toast_success.png';

  static const String commonUncheckRound = 'assets/images/common/uncheck_round.png';

  static const String commonVipBg = 'assets/images/common/vip_bg.png';

  static const String countryAfghanistan = 'assets/images/country/Afghanistan.png';

  static const String countryAlandIslands = 'assets/images/country/Aland_Islands.png';

  static const String countryAlbania = 'assets/images/country/Albania.png';

  static const String countryAlgeria = 'assets/images/country/Algeria.png';

  static const String countryAmerica = 'assets/images/country/America.png';

  static const String countryAmericanSamoa = 'assets/images/country/American_Samoa.png';

  static const String countryAndorra = 'assets/images/country/Andorra.png';

  static const String countryAngola = 'assets/images/country/Angola.png';

  static const String countryAnguilla = 'assets/images/country/Anguilla.png';

  static const String countryAntarctica = 'assets/images/country/Antarctica.png';

  static const String countryAntiguaAndBarbuda = 'assets/images/country/Antigua_and_Barbuda.png';

  static const String countryArgentina = 'assets/images/country/Argentina.png';

  static const String countryArmenia = 'assets/images/country/Armenia.png';

  static const String countryAruba = 'assets/images/country/Aruba.png';

  static const String countryAustralia = 'assets/images/country/Australia.png';

  static const String countryAustria = 'assets/images/country/Austria.png';

  static const String countryAzerbaijan = 'assets/images/country/Azerbaijan.png';

  static const String countryBahamas = 'assets/images/country/Bahamas.png';

  static const String countryBahrain = 'assets/images/country/Bahrain.png';

  static const String countryBangladesh = 'assets/images/country/Bangladesh.png';

  static const String countryBarbados = 'assets/images/country/Barbados.png';

  static const String countryBelarus = 'assets/images/country/Belarus.png';

  static const String countryBelgium = 'assets/images/country/Belgium.png';

  static const String countryBelize = 'assets/images/country/Belize.png';

  static const String countryBenin = 'assets/images/country/Benin.png';

  static const String countryBermudaIs = 'assets/images/country/Bermuda_Is.png';

  static const String countryBhutan = 'assets/images/country/Bhutan.png';

  static const String countryBolivia = 'assets/images/country/Bolivia.png';

  static const String countryBosniaAndHerzegovina = 'assets/images/country/Bosnia_and_Herzegovina.png';

  static const String countryBotswana = 'assets/images/country/Botswana.png';

  static const String countryBouvetIsland = 'assets/images/country/Bouvet_Island.png';

  static const String countryBrazil = 'assets/images/country/Brazil.png';

  static const String countryBritishIndianOceanTerritory = 'assets/images/country/British_Indian_Ocean_Territory.png';

  static const String countryBritishVirginIslands = 'assets/images/country/British_Virgin_Islands.png';

  static const String countryBrunei = 'assets/images/country/Brunei.png';

  static const String countryBulgaria = 'assets/images/country/Bulgaria.png';

  static const String countryBurkinaFaso = 'assets/images/country/Burkina-faso.png';

  static const String countryBurma = 'assets/images/country/Burma.png';

  static const String countryBurundi = 'assets/images/country/Burundi.png';

  static const String countryCambodia = 'assets/images/country/Cambodia.png';

  static const String countryCameroon = 'assets/images/country/Cameroon.png';

  static const String countryCanada = 'assets/images/country/Canada.png';

  static const String countryCapeVerde = 'assets/images/country/Cape_Verde.png';

  static const String countryCaymanIs = 'assets/images/country/Cayman_Is.png';

  static const String countryCentralAfricanRepublic = 'assets/images/country/Central_African_Republic.png';

  static const String countryChad = 'assets/images/country/Chad.png';

  static const String countryChile = 'assets/images/country/Chile.png';

  static const String countryChina = 'assets/images/country/China.png';

  static const String countryChristmasIsland = 'assets/images/country/Christmas_Island.png';

  static const String countryCocosIslands = 'assets/images/country/Cocos_Islands.png';

  static const String countryColombia = 'assets/images/country/Colombia.png';

  static const String countryComoros = 'assets/images/country/Comoros.png';

  static const String countryCongo = 'assets/images/country/Congo.png';

  static const String countryCookIs = 'assets/images/country/Cook_Is.png';

  static const String countryCostaRica = 'assets/images/country/Costa_Rica.png';

  static const String countryCoteDIvoire = 'assets/images/country/Cote_dIvoire.png';

  static const String countryCroatia = 'assets/images/country/Croatia.png';

  static const String countryCuba = 'assets/images/country/Cuba.png';

  static const String countryCuracao = 'assets/images/country/Curacao.png';

  static const String countryCyprus = 'assets/images/country/Cyprus.png';

  static const String countryCzechRepublic = 'assets/images/country/Czech_Republic.png';

  static const String countryDenmark = 'assets/images/country/Denmark.png';

  static const String countryDjibouti = 'assets/images/country/Djibouti.png';

  static const String countryDominicaRep = 'assets/images/country/Dominica_Rep.png';

  static const String countryDominicanRepublic = 'assets/images/country/Dominican_Republic.png';

  static const String countryEISalvador = 'assets/images/country/EISalvador.png';

  static const String countryEcuador = 'assets/images/country/Ecuador.png';

  static const String countryEgypt = 'assets/images/country/Egypt.png';

  static const String countryEquatorialGuinea = 'assets/images/country/Equatorial_Guinea.png';

  static const String countryEritrea = 'assets/images/country/Eritrea.png';

  static const String countryEstonia = 'assets/images/country/Estonia.png';

  static const String countryEthiopia = 'assets/images/country/Ethiopia.png';

  static const String countryFalklandIslands = 'assets/images/country/Falkland_Islands.png';

  static const String countryFaroeIslands = 'assets/images/country/Faroe_Islands.png';

  static const String countryFiji = 'assets/images/country/Fiji.png';

  static const String countryFinland = 'assets/images/country/Finland.png';

  static const String countryFrance = 'assets/images/country/France.png';

  static const String countryFrenchGuiana = 'assets/images/country/French_Guiana.png';

  static const String countryFrenchPolynesia = 'assets/images/country/French_Polynesia.png';

  static const String countryFrenchSouthernTerritories = 'assets/images/country/French_Southern_Territories.png';

  static const String countryGabon = 'assets/images/country/Gabon.png';

  static const String countryGambia = 'assets/images/country/Gambia.png';

  static const String countryGeorgia = 'assets/images/country/Georgia.png';

  static const String countryGermany = 'assets/images/country/Germany.png';

  static const String countryGhana = 'assets/images/country/Ghana.png';

  static const String countryGibraltar = 'assets/images/country/Gibraltar.png';

  static const String countryGreece = 'assets/images/country/Greece.png';

  static const String countryGreenland = 'assets/images/country/Greenland.png';

  static const String countryGrenada = 'assets/images/country/Grenada.png';

  static const String countryGuadeloupe = 'assets/images/country/Guadeloupe.png';

  static const String countryGuam = 'assets/images/country/Guam.png';

  static const String countryGuatemala = 'assets/images/country/Guatemala.png';

  static const String countryGuernsey = 'assets/images/country/Guernsey.png';

  static const String countryGuineaBissau = 'assets/images/country/Guinea-Bissau.png';

  static const String countryGuinea = 'assets/images/country/Guinea.png';

  static const String countryGuyana = 'assets/images/country/Guyana.png';

  static const String countryHaiti = 'assets/images/country/Haiti.png';

  static const String countryHeardIslandAndMcDonaldIslands = 'assets/images/country/Heard_Island_and_McDonald_Islands.png';

  static const String countryHonduras = 'assets/images/country/Honduras.png';

  static const String countryHongkong = 'assets/images/country/Hongkong.png';

  static const String countryHungary = 'assets/images/country/Hungary.png';

  static const String countryIceland = 'assets/images/country/Iceland.png';

  static const String countryIndia = 'assets/images/country/India.png';

  static const String countryIndonesia = 'assets/images/country/Indonesia.png';

  static const String countryIran = 'assets/images/country/Iran.png';

  static const String countryIraq = 'assets/images/country/Iraq.png';

  static const String countryIreland = 'assets/images/country/Ireland.png';

  static const String countryIsleOfMan = 'assets/images/country/Isle_of_Man.png';

  static const String countryIsrael = 'assets/images/country/Israel.png';

  static const String countryItaly = 'assets/images/country/Italy.png';

  static const String countryIvoryCoast = 'assets/images/country/Ivory_Coast.png';

  static const String countryJamaica = 'assets/images/country/Jamaica.png';

  static const String countryJapan = 'assets/images/country/Japan.png';

  static const String countryJersey = 'assets/images/country/Jersey.png';

  static const String countryJordan = 'assets/images/country/Jordan.png';

  static const String countryKazakstan = 'assets/images/country/Kazakstan.png';

  static const String countryKenya = 'assets/images/country/Kenya.png';

  static const String countryKiribati = 'assets/images/country/Kiribati.png';

  static const String countryKorea = 'assets/images/country/Korea.png';

  static const String countryKosovo = 'assets/images/country/Kosovo.png';

  static const String countryKuwait = 'assets/images/country/Kuwait.png';

  static const String countryKyrgyzstan = 'assets/images/country/Kyrgyzstan.png';

  static const String countryLaos = 'assets/images/country/Laos.png';

  static const String countryLatvia = 'assets/images/country/Latvia.png';

  static const String countryLebanon = 'assets/images/country/Lebanon.png';

  static const String countryLesotho = 'assets/images/country/Lesotho.png';

  static const String countryLiberia = 'assets/images/country/Liberia.png';

  static const String countryLibya = 'assets/images/country/Libya.png';

  static const String countryLiechtenstein = 'assets/images/country/Liechtenstein.png';

  static const String countryLithuania = 'assets/images/country/Lithuania.png';

  static const String countryLuxembourg = 'assets/images/country/Luxembourg.png';

  static const String countryMacao = 'assets/images/country/Macao.png';

  static const String countryMacedonia = 'assets/images/country/Macedonia.png';

  static const String countryMadagascar = 'assets/images/country/Madagascar.png';

  static const String countryMalawi = 'assets/images/country/Malawi.png';

  static const String countryMalaysia = 'assets/images/country/Malaysia.png';

  static const String countryMaldives = 'assets/images/country/Maldives.png';

  static const String countryMali = 'assets/images/country/Mali.png';

  static const String countryMalta = 'assets/images/country/Malta.png';

  static const String countryMarianaIs = 'assets/images/country/MarianaIs.png';

  static const String countryMarshallIslands = 'assets/images/country/Marshall_Islands.png';

  static const String countryMartinique = 'assets/images/country/Martinique.png';

  static const String countryMauritania = 'assets/images/country/Mauritania.png';

  static const String countryMauritius = 'assets/images/country/Mauritius.png';

  static const String countryMayotte = 'assets/images/country/Mayotte.png';

  static const String countryMexico = 'assets/images/country/Mexico.png';

  static const String countryMicronesia = 'assets/images/country/Micronesia.png';

  static const String countryMoldovaRepublicOf = 'assets/images/country/Moldova_RepublicOf.png';

  static const String countryMonaco = 'assets/images/country/Monaco.png';

  static const String countryMongolia = 'assets/images/country/Mongolia.png';

  static const String countryMontenegro = 'assets/images/country/Montenegro.png';

  static const String countryMontserratIs = 'assets/images/country/MontserratIs.png';

  static const String countryMorocco = 'assets/images/country/Morocco.png';

  static const String countryMozambique = 'assets/images/country/Mozambique.png';

  static const String countryMyanmar = 'assets/images/country/Myanmar.png';

  static const String countryNamibia = 'assets/images/country/Namibia.png';

  static const String countryNauru = 'assets/images/country/Nauru.png';

  static const String countryNepal = 'assets/images/country/Nepal.png';

  static const String countryNetheriandsAntilles = 'assets/images/country/Netheriands_Antilles.png';

  static const String countryNetherlands = 'assets/images/country/Netherlands.png';

  static const String countryNewCaledonia = 'assets/images/country/New_Caledonia.png';

  static const String countryNewZealand = 'assets/images/country/New_Zealand.png';

  static const String countryNicaragua = 'assets/images/country/Nicaragua.png';

  static const String countryNiger = 'assets/images/country/Niger.png';

  static const String countryNigeria = 'assets/images/country/Nigeria.png';

  static const String countryNiue = 'assets/images/country/Niue.png';

  static const String countryNorfolkIsland = 'assets/images/country/Norfolk_Island.png';

  static const String countryNorthKorea = 'assets/images/country/North_Korea.png';

  static const String countryNorway = 'assets/images/country/Norway.png';

  static const String countryOman = 'assets/images/country/Oman.png';

  static const String countryPakistan = 'assets/images/country/Pakistan.png';

  static const String countryPalau = 'assets/images/country/Palau.png';

  static const String countryPalestine = 'assets/images/country/Palestine.png';

  static const String countryPanama = 'assets/images/country/Panama.png';

  static const String countryPapuaNewCuinea = 'assets/images/country/Papua_New_Cuinea.png';

  static const String countryParaguay = 'assets/images/country/Paraguay.png';

  static const String countryPeru = 'assets/images/country/Peru.png';

  static const String countryPhilippines = 'assets/images/country/Philippines.png';

  static const String countryPitcairnIslands = 'assets/images/country/Pitcairn_Islands.png';

  static const String countryPoland = 'assets/images/country/Poland.png';

  static const String countryPortugal = 'assets/images/country/Portugal.png';

  static const String countryPuertoRico = 'assets/images/country/Puerto_Rico.png';

  static const String countryQatar = 'assets/images/country/Qatar.png';

  static const String countryReunion = 'assets/images/country/Reunion.png';

  static const String countryRomania = 'assets/images/country/Romania.png';

  static const String countryRussia = 'assets/images/country/Russia.png';

  static const String countryRwanda = 'assets/images/country/Rwanda.png';

  static const String countrySaintBarthelemy = 'assets/images/country/Saint_Barthelemy.png';

  static const String countrySaintHelena = 'assets/images/country/Saint_Helena.png';

  static const String countrySaintKittsAndNevis = 'assets/images/country/Saint_Kitts_and_Nevis.png';

  static const String countrySaintLueia = 'assets/images/country/Saint_Lueia.png';

  static const String countrySaintMartin = 'assets/images/country/Saint_Martin.png';

  static const String countrySaintPierreAndMiquelon = 'assets/images/country/Saint_Pierre_and_Miquelon.png';

  static const String countrySaintVincent = 'assets/images/country/Saint_Vincent.png';

  static const String countrySamoa = 'assets/images/country/Samoa.png';

  static const String countrySanMarino = 'assets/images/country/San_Marino.png';

  static const String countrySaoTomeAndPrincipe = 'assets/images/country/Sao_Tome_and_Principe.png';

  static const String countrySaudiArabia = 'assets/images/country/Saudi_Arabia.png';

  static const String countrySenegal = 'assets/images/country/Senegal.png';

  static const String countrySerbia = 'assets/images/country/Serbia.png';

  static const String countrySeychelles = 'assets/images/country/Seychelles.png';

  static const String countrySierraLeone = 'assets/images/country/Sierra_Leone.png';

  static const String countrySingapore = 'assets/images/country/Singapore.png';

  static const String countrySintEustatius = 'assets/images/country/Sint_Eustatius.png';

  static const String countrySintMaarten = 'assets/images/country/Sint_Maarten.png';

  static const String countrySlovakia = 'assets/images/country/Slovakia.png';

  static const String countrySlovenia = 'assets/images/country/Slovenia.png';

  static const String countrySolomonIs = 'assets/images/country/SolomonIs.png';

  static const String countrySomali = 'assets/images/country/Somali.png';

  static const String countrySouthAfrica = 'assets/images/country/SouthAfrica.png';

  static const String countrySouthGeorgiaAndTheSouthSandwichIslands = 'assets/images/country/South_Georgia_and_the_South_Sandwich_Islands.png';

  static const String countrySpain = 'assets/images/country/Spain.png';

  static const String countrySriLanka = 'assets/images/country/SriLanka.png';

  static const String countryStLucia = 'assets/images/country/StLucia.png';

  static const String countryStVincent = 'assets/images/country/StVincent.png';

  static const String countrySudan = 'assets/images/country/Sudan.png';

  static const String countrySuriname = 'assets/images/country/Suriname.png';

  static const String countrySvalbardAndJanMayen = 'assets/images/country/Svalbard_and_Jan_Mayen.png';

  static const String countrySwaziland = 'assets/images/country/Swaziland.png';

  static const String countrySweden = 'assets/images/country/Sweden.png';

  static const String countrySwitzerland = 'assets/images/country/Switzerland.png';

  static const String countrySyria = 'assets/images/country/Syria.png';

  static const String countryTaiwan = 'assets/images/country/Taiwan.png';

  static const String countryTajikstan = 'assets/images/country/Tajikstan.png';

  static const String countryTanzania = 'assets/images/country/Tanzania.png';

  static const String countryThailand = 'assets/images/country/Thailand.png';

  static const String countryTogo = 'assets/images/country/Togo.png';

  static const String countryTokelau = 'assets/images/country/Tokelau.png';

  static const String countryTonga = 'assets/images/country/Tonga.png';

  static const String countryTrinidadAndTobago = 'assets/images/country/Trinidad_and_Tobago.png';

  static const String countryTunisia = 'assets/images/country/Tunisia.png';

  static const String countryTurkey = 'assets/images/country/Turkey.png';

  static const String countryTurkmenistan = 'assets/images/country/Turkmenistan.png';

  static const String countryTurksAndCaicosIslands = 'assets/images/country/Turks_and_Caicos_Islands.png';

  static const String countryTuvalu = 'assets/images/country/Tuvalu.png';

  static const String countryUganda = 'assets/images/country/Uganda.png';

  static const String countryUkraine = 'assets/images/country/Ukraine.png';

  static const String countryUnitedArabEmirates = 'assets/images/country/United_Arab_Emirates.png';

  static const String countryUnitedKingdom = 'assets/images/country/United_Kingdom.png';

  static const String countryUnitedKiongdom = 'assets/images/country/United_Kiongdom.png';

  static const String countryUnitedStatesVirginIslands = 'assets/images/country/United_States_Virgin_Islands.png';

  static const String countryUruguay = 'assets/images/country/Uruguay.png';

  static const String countryUzbekistan = 'assets/images/country/Uzbekistan.png';

  static const String countryVanuata = 'assets/images/country/Vanuata.png';

  static const String countryVaticanCity = 'assets/images/country/Vatican_City.png';

  static const String countryVenezuela = 'assets/images/country/Venezuela.png';

  static const String countryVietnam = 'assets/images/country/Vietnam.png';

  static const String countryWallisAndFutuna = 'assets/images/country/Wallis_and_Futuna.png';

  static const String countryYemen = 'assets/images/country/Yemen.png';

  static const String countryYugoslavia = 'assets/images/country/Yugoslavia.png';

  static const String countryZaire = 'assets/images/country/Zaire.png';

  static const String countryZambia = 'assets/images/country/Zambia.png';

  static const String countryZimbabwe = 'assets/images/country/Zimbabwe.png';

  static const String couponBgHighlight = 'assets/images/coupon/bg_highlight.svg';

  static const String couponBgHighlightDay = 'assets/images/coupon/bg_highlight_day.svg';

  static const String couponBgNormal = 'assets/images/coupon/bg_normal.svg';

  static const String couponBgNormalDay = 'assets/images/coupon/bg_normal_day.svg';

  static const String couponCouponCodeIcon = 'assets/images/coupon/coupon_code_icon.png';

  static const String couponCouponSort = 'assets/images/coupon/coupon_sort.png';

  static const String couponDoubleArrowRight = 'assets/images/coupon/double_arrow_right.svg';

  static const String couponExplain = 'assets/images/coupon/explain.svg';

  static const String currencyUSDC = 'assets/images/currency/USDC.svg';

  static const String currencyWithdrawGuide = 'assets/images/currency/withdraw_guide.png';

  static const String depositCreditCard = 'assets/images/deposit/credit_card.png';

  static const String depositCrypto = 'assets/images/deposit/crypto.png';

  static const String depositCurrency = 'assets/images/deposit/currency.png';

  static const String gameExitGame = 'assets/images/game/exit_game.svg';

  static const String gameFullGame = 'assets/images/game/full_game.svg';

  static const String gameGameCollectBack = 'assets/images/game/game_collect_back.png';

  static const String gameGameCoverCh = 'assets/images/game/game_cover_ch.png';

  static const String gameGameCoverEn = 'assets/images/game/game_cover_en.png';

  static const String gameGameExplain = 'assets/images/game/game_explain.png';

  static const String gameGameLobby = 'assets/images/game/game_lobby.png';

  static const String gameGameLuckyResultFail = 'assets/images/game/game_lucky_result_fail.png';

  static const String gameGameLuckyResultSuccess = 'assets/images/game/game_lucky_result_success.png';

  static const String gameGameMusic = 'assets/images/game/game_music.png';

  static const String gameGameMusicClose = 'assets/images/game/game_music_close.png';

  static const String gameGameMusicClosePng = 'assets/images/game/game_music_close_png.png';

  static const String gameGameMusicOpen = 'assets/images/game/game_music_open.png';

  static const String gameGameProBack = 'assets/images/game/game_pro_back.png';

  static const String gameGameRecBack = 'assets/images/game/game_rec_back.png';

  static const String gameInviteBg = 'assets/images/game/invite_bg.png';

  static const String gameInviteBgTop = 'assets/images/game/invite_bg_top.png';

  static const String gameLuckySpinBg = 'assets/images/game/lucky_spin_bg.png';

  static const String gameLuckySpinMask = 'assets/images/game/lucky_spin_mask.png';

  static const String gameLuckyTurntableArrow = 'assets/images/game/lucky_turntable_arrow.png';

  static const String gameLuckyTurntableBg = 'assets/images/game/lucky_turntable_bg.png';

  static const String gameLuckyTurntableCycBottomleft = 'assets/images/game/lucky_turntable_cyc_bottomleft.svg';

  static const String gameLuckyTurntableCycBottomright = 'assets/images/game/lucky_turntable_cyc_bottomright.svg';

  static const String gameLuckyTurntableCycHalfLeft = 'assets/images/game/lucky_turntable_cyc_half_left.svg';

  static const String gameLuckyTurntableCycHalfRight = 'assets/images/game/lucky_turntable_cyc_half_right.svg';

  static const String gameLuckyTurntableCycTopleft = 'assets/images/game/lucky_turntable_cyc_topleft.svg';

  static const String gameLuckyTurntableCycTopright = 'assets/images/game/lucky_turntable_cyc_topright.svg';

  static const String gameShrinkGame = 'assets/images/game/shrink_game.svg';

  static const String gameSortAZ = 'assets/images/game/sort_AZ.svg';

  static const String gameSortHighlights = 'assets/images/game/sort_Highlights.svg';

  static const String gameSortHot = 'assets/images/game/sort_Hot.svg';

  static const String gameSortRecommendSort = 'assets/images/game/sort_RecommendSort.svg';

  static const String gameSortZA = 'assets/images/game/sort_ZA.svg';

  static const String gameConfigFBty = 'assets/images/game_config/FBty.svg';

  static const String gameConfigIMdj = 'assets/images/game_config/IMdj.svg';

  static const String gameConfigIMty = 'assets/images/game_config/IMty.svg';

  static const String gameConfigPBdj = 'assets/images/game_config/PBdj.svg';

  static const String gameConfigPBty = 'assets/images/game_config/PBty.svg';

  static const String gameConfigPMty = 'assets/images/game_config/PMty.svg';

  static const String gameConfigSBty = 'assets/images/game_config/SBty.svg';

  static const String gameConfigTFdj = 'assets/images/game_config/TFdj.svg';

  static const String home1th = 'assets/images/home/1th.png';

  static const String home2th = 'assets/images/home/2th.png';

  static const String home3th = 'assets/images/home/3th.png';

  static const String homeCountdown = 'assets/images/home/countdown.svg';

  static const String homeOriginalGamingBg = 'assets/images/home/original_gaming_bg.jpg';

  static const String homeRocket = 'assets/images/home/rocket.gif';

  static const String homeStatistics = 'assets/images/home/statistics.svg';

  static const String homeTitle1 = 'assets/images/home/title1.svg';

  static const String homeTitle2 = 'assets/images/home/title2.svg';

  static const String homeTitle3 = 'assets/images/home/title3.svg';

  static const String iconAdd = 'assets/images/icon/add.svg';

  static const String iconAddFill = 'assets/images/icon/add_fill.svg';

  static const String iconAppbarLeftLeading = 'assets/images/icon/appbar_left_leading.svg';

  static const String iconArrowDown = 'assets/images/icon/arrow_down.svg';

  static const String iconArrowLeft = 'assets/images/icon/arrow_left.svg';

  static const String iconArrowLeftAlt = 'assets/images/icon/arrow_left_alt.svg';

  static const String iconArrowRight = 'assets/images/icon/arrow_right.svg';

  static const String iconArrowRightAlt = 'assets/images/icon/arrow_right_alt.svg';

  static const String iconArrowUp = 'assets/images/icon/arrow_up.svg';

  static const String iconAvatarUpload = 'assets/images/icon/avatar_upload.png';

  static const String iconBindSuccess = 'assets/images/icon/bind_success.png';

  static const String iconCalendar = 'assets/images/icon/calendar.svg';

  static const String iconCalendar2 = 'assets/images/icon/calendar2.svg';

  static const String iconCamera = 'assets/images/icon/camera.svg';

  static const String iconCancel = 'assets/images/icon/cancel.svg';

  static const String iconCancelIcon = 'assets/images/icon/cancel_icon.png';

  static const String iconChecked = 'assets/images/icon/checked.svg';

  static const String iconClose = 'assets/images/icon/close.svg';

  static const String iconCopy = 'assets/images/icon/copy.svg';

  static const String iconCopy2 = 'assets/images/icon/copy2.svg';

  static const String iconCurrencyAll = 'assets/images/icon/currency_all.png';

  static const String iconDelete = 'assets/images/icon/delete.svg';

  static const String iconDelete2 = 'assets/images/icon/delete2.svg';

  static const String iconDown = 'assets/images/icon/down.svg';

  static const String iconDownload = 'assets/images/icon/download.svg';

  static const String iconDropDown = 'assets/images/icon/drop_down.svg';

  static const String iconEdit = 'assets/images/icon/edit.svg';

  static const String iconEdit2 = 'assets/images/icon/edit2.svg';

  static const String iconFilter = 'assets/images/icon/filter.svg';

  static const String iconFreezeError = 'assets/images/icon/freeze_error.png';

  static const String iconGame = 'assets/images/icon/game.svg';

  static const String iconGiftCard = 'assets/images/icon/gift_card.png';

  static const String iconGoDetail = 'assets/images/icon/go_detail.png';

  static const String iconGoDetailDay = 'assets/images/icon/go_detail_day.png';

  static const String iconHelpGuide = 'assets/images/icon/help_guide.svg';

  static const String iconHistorySift = 'assets/images/icon/history_sift.svg';

  static const String iconIconRight = 'assets/images/icon/icon_right.svg';

  static const String iconImageError = 'assets/images/icon/image_error.svg';

  static const String iconLock = 'assets/images/icon/lock.svg';

  static const String iconMobilePhone = 'assets/images/icon/mobile_phone.png';

  static const String iconMore = 'assets/images/icon/more.svg';

  static const String iconNoEmailCode = 'assets/images/icon/no_email_code.png';

  static const String iconNoRegisterCode = 'assets/images/icon/no_register_code.png';

  static const String iconNotifyIcon = 'assets/images/icon/notify_icon.png';

  static const String iconPlay = 'assets/images/icon/play.svg';

  static const String iconQuestion = 'assets/images/icon/question.svg';

  static const String iconRadioChecked = 'assets/images/icon/radio_checked.svg';

  static const String iconRadioUnChecked = 'assets/images/icon/radio_un_checked.svg';

  static const String iconReduce = 'assets/images/icon/reduce.svg';

  static const String iconReduceFill = 'assets/images/icon/reduce_fill.svg';

  static const String iconRequired = 'assets/images/icon/required.svg';

  static const String iconResultFailed = 'assets/images/icon/result_failed.png';

  static const String iconRiskError = 'assets/images/icon/risk_error.svg';

  static const String iconRocketBgNew = 'assets/images/icon/rocket_bg_new.png';

  static const String iconRocketNew = 'assets/images/icon/rocket_new.png';

  static const String iconSafety = 'assets/images/icon/safety.svg';

  static const String iconScan = 'assets/images/icon/scan.svg';

  static const String iconSearch = 'assets/images/icon/search.svg';

  static const String iconSearch2 = 'assets/images/icon/search2.svg';

  static const String iconSecureOff = 'assets/images/icon/secure_off.svg';

  static const String iconSecureOn = 'assets/images/icon/secure_on.svg';

  static const String iconSetting = 'assets/images/icon/setting.svg';

  static const String iconShare = 'assets/images/icon/share.svg';

  static const String iconShare2 = 'assets/images/icon/share2.svg';

  static const String iconSortAscending = 'assets/images/icon/sort_ascending.svg';

  static const String iconSortDescending = 'assets/images/icon/sort_descending.svg';

  static const String iconSortDragBtn = 'assets/images/icon/sort_drag_btn.svg';

  static const String iconSortMenu = 'assets/images/icon/sort_menu.svg';

  static const String iconStar = 'assets/images/icon/star.svg';

  static const String iconStarFill = 'assets/images/icon/star_fill.svg';

  static const String iconTipIcon = 'assets/images/icon/tip_icon.svg';

  static const String iconToastClose = 'assets/images/icon/toast_close.svg';

  static const String iconTransfer = 'assets/images/icon/transfer.svg';

  static const String iconTransferArrows = 'assets/images/icon/transfer_arrows.svg';

  static const String iconTransferChange = 'assets/images/icon/transfer_change.png';

  static const String iconTransferFromIcon = 'assets/images/icon/transfer_from_icon.svg';

  static const String iconTransferHistory = 'assets/images/icon/transfer_history.svg';

  static const String iconTransferLeftDot = 'assets/images/icon/transfer_left_dot.svg';

  static const String iconTransferToIcon = 'assets/images/icon/transfer_to_icon.svg';

  static const String iconTriangle = 'assets/images/icon/triangle.svg';

  static const String iconUp = 'assets/images/icon/up.svg';

  static const String iconUpload = 'assets/images/icon/upload.svg';

  static const String iconUploadCloud = 'assets/images/icon/upload_cloud.svg';

  static const String iconUseExplain = 'assets/images/icon/use_explain.svg';

  static const String iconVerifyFailed = 'assets/images/icon/verify_failed.svg';

  static const String iconVerifySuccessful = 'assets/images/icon/verify_successful.svg';

  static const String iconVersionBg = 'assets/images/icon/version_bg.svg';

  static const String iconVideoTutorial = 'assets/images/icon/video_tutorial.svg';

  static const String iconVisibility = 'assets/images/icon/visibility.svg';

  static const String iconVisibilityOff = 'assets/images/icon/visibility_off.svg';

  static const String iconWalletHome = 'assets/images/icon/wallet_home.svg';

  static const String iconWalletSetting = 'assets/images/icon/wallet_setting.svg';

  static const String iconWarning = 'assets/images/icon/warning.svg';

  static const String kycCalendar = 'assets/images/kyc/calendar.png';

  static const String kycCardTip0 = 'assets/images/kyc/card_tip0.png';

  static const String kycCardTip1 = 'assets/images/kyc/card_tip1.png';

  static const String kycCardTip2 = 'assets/images/kyc/card_tip2.png';

  static const String kycCardTip3 = 'assets/images/kyc/card_tip3.png';

  static const String kycCircleCheckedGreen = 'assets/images/kyc/circle_checked_green.svg';

  static const String kycCircleCheckedWhite = 'assets/images/kyc/circle_checked_white.svg';

  static const String kycImageUpload = 'assets/images/kyc/image_upload.png';

  static const String kycKycAdvanceLimitIcon2 = 'assets/images/kyc/kyc_advance_limit_icon2.svg';

  static const String kycKycAvatar = 'assets/images/kyc/kyc_avatar.svg';

  static const String kycKycCamera = 'assets/images/kyc/kyc_camera.png';

  static const String kycKycCheck = 'assets/images/kyc/kyc_check.svg';

  static const String kycKycClose = 'assets/images/kyc/kyc_close.svg';

  static const String kycKycDriverLicense = 'assets/images/kyc/kyc_driver_license.png';

  static const String kycKycEdit = 'assets/images/kyc/kyc_edit.svg';

  static const String kycKycIdcard = 'assets/images/kyc/kyc_idcard.png';

  static const String kycKycMiddleLimitIcon1 = 'assets/images/kyc/kyc_middle_limit_icon1.svg';

  static const String kycKycMiddleLimitIcon2 = 'assets/images/kyc/kyc_middle_limit_icon2.svg';

  static const String kycKycMiddleLimitIcon3 = 'assets/images/kyc/kyc_middle_limit_icon3.svg';

  static const String kycKycMiddleLimitIcon4 = 'assets/images/kyc/kyc_middle_limit_icon4.svg';

  static const String kycKycMiddleLimitIcon5 = 'assets/images/kyc/kyc_middle_limit_icon5.svg';

  static const String kycKycNotVerify = 'assets/images/kyc/kyc_not_verify.svg';

  static const String kycKycPass = 'assets/images/kyc/kyc_pass.svg';

  static const String kycKycPassport = 'assets/images/kyc/kyc_passport.png';

  static const String kycKycPendingIcon = 'assets/images/kyc/kyc_pending_icon.svg';

  static const String kycKycPrivacy = 'assets/images/kyc/kyc_privacy.svg';

  static const String kycKycResultError = 'assets/images/kyc/kyc_result_error.svg';

  static const String loginRegisterBiometricLogin = 'assets/images/login_register/biometric_login.png';

  static const String loginRegisterCheckBox = 'assets/images/login_register/check_box.png';

  static const String loginRegisterCheckBoxBlue = 'assets/images/login_register/check_box_blue.png';

  static const String loginRegisterUncheckBox = 'assets/images/login_register/uncheck_box.png';

  static const String lotteryGPILottery = 'assets/images/lottery/GPILottery.png';

  static const String lotteryP3P5 = 'assets/images/lottery/P3P5.png';

  static const String lotteryPMLottery = 'assets/images/lottery/PMLottery.png';

  static const String lotterySGLottery = 'assets/images/lottery/SGLottery.png';

  static const String lotteryTCLottery = 'assets/images/lottery/TCLottery.png';

  static const String lotteryVRLottery = 'assets/images/lottery/VRLottery.png';

  static const String lotteryAll = 'assets/images/lottery/all.png';

  static const String lotteryDipin = 'assets/images/lottery/dipin.png';

  static const String lotteryEleFive = 'assets/images/lottery/ele_five.png';

  static const String lotteryInLott = 'assets/images/lottery/in_lott.png';

  static const String lotteryKThree = 'assets/images/lottery/k_three.png';

  static const String lotteryKeno = 'assets/images/lottery/keno.png';

  static const String lotteryLeagueLegends = 'assets/images/lottery/league_legends.png';

  static const String lotteryLotto = 'assets/images/lottery/lotto.png';

  static const String lotteryMenuDipin = 'assets/images/lottery/menu_dipin.png';

  static const String lotteryMenuEleFive = 'assets/images/lottery/menu_ele_five.png';

  static const String lotteryMenuInLott = 'assets/images/lottery/menu_in_lott.png';

  static const String lotteryMenuKThree = 'assets/images/lottery/menu_k_three.png';

  static const String lotteryMenuKeno = 'assets/images/lottery/menu_keno.png';

  static const String lotteryMenuLeagueLegends = 'assets/images/lottery/menu_league_legends.png';

  static const String lotteryMenuLotto = 'assets/images/lottery/menu_lotto.png';

  static const String lotteryMenuPkTen = 'assets/images/lottery/menu_pk_ten.png';

  static const String lotteryMenuShaibao = 'assets/images/lottery/menu_shaibao.png';

  static const String lotteryMenuShuanseqiu = 'assets/images/lottery/menu_shuanseqiu.png';

  static const String lotteryMenuSsc = 'assets/images/lottery/menu_ssc.png';

  static const String lotteryMenuThreed = 'assets/images/lottery/menu_threed.png';

  static const String lotteryMenuVnc = 'assets/images/lottery/menu_vnc.png';

  static const String lotteryMenuWanzifour = 'assets/images/lottery/menu_wanzifour.png';

  static const String lotteryPkTen = 'assets/images/lottery/pk_ten.png';

  static const String lotteryShaibao = 'assets/images/lottery/shaibao.png';

  static const String lotteryShuanseqiu = 'assets/images/lottery/shuanseqiu.png';

  static const String lotterySsc = 'assets/images/lottery/ssc.png';

  static const String lotteryThreed = 'assets/images/lottery/threed.png';

  static const String lotteryVnc = 'assets/images/lottery/vnc.png';

  static const String lotteryWanzifour = 'assets/images/lottery/wanzifour.png';

  static const String mainMenuAboutUs = 'assets/images/main_menu/about_us.svg';

  static const String mainMenuAboutUsBack = 'assets/images/main_menu/about_us_back.png';

  static const String mainMenuAccountSafe = 'assets/images/main_menu/account_safe.svg';

  static const String mainMenuByqp = 'assets/images/main_menu/byqp.svg';

  static const String mainMenuCardCenter = 'assets/images/main_menu/card_center.svg';

  static const String mainMenuCountriesCn = 'assets/images/main_menu/countries_cn.png';

  static const String mainMenuCountriesEn = 'assets/images/main_menu/countries_en.png';

  static const String mainMenuCountriesTh = 'assets/images/main_menu/countries_th.png';

  static const String mainMenuCountriesVi = 'assets/images/main_menu/countries_vi.png';

  static const String mainMenuDailyContestBack = 'assets/images/main_menu/daily_contest_back.png';

  static const String mainMenuDailyContestMask = 'assets/images/main_menu/daily_contest_mask.png';

  static const String mainMenuDayMode = 'assets/images/main_menu/day_mode.png';

  static const String mainMenuDiamonds = 'assets/images/main_menu/diamonds.svg';

  static const String mainMenuEarnedCommission = 'assets/images/main_menu/earned_commission.svg';

  static const String mainMenuEntertainment = 'assets/images/main_menu/entertainment.png';

  static const String mainMenuExit = 'assets/images/main_menu/exit.svg';

  static const String mainMenuFreeGuessBack = 'assets/images/main_menu/free_guess_back.png';

  static const String mainMenuFreeGuessMask = 'assets/images/main_menu/free_guess_mask.png';

  static const String mainMenuGambling = 'assets/images/main_menu/gambling.svg';

  static const String mainMenuGdqp = 'assets/images/main_menu/gdqp.svg';

  static const String mainMenuGeneral = 'assets/images/main_menu/general.svg';

  static const String mainMenuGpiqp = 'assets/images/main_menu/gpiqp.svg';

  static const String mainMenuHelp = 'assets/images/main_menu/help.svg';

  static const String mainMenuIconLeft = 'assets/images/main_menu/icon_left.svg';

  static const String mainMenuImdj = 'assets/images/main_menu/imdj.svg';

  static const String mainMenuKyqp = 'assets/images/main_menu/kyqp.svg';

  static const String mainMenuLottery = 'assets/images/main_menu/lottery.png';

  static const String mainMenuLuckSpinBack = 'assets/images/main_menu/luck_spin_back.png';

  static const String mainMenuLuckSpinGold = 'assets/images/main_menu/luck_spin_gold.png';

  static const String mainMenuLuckSpinWheel = 'assets/images/main_menu/luck_spin_wheel.png';

  static const String mainMenuMyCollect = 'assets/images/main_menu/my_collect.svg';

  static const String mainMenuNewActivity = 'assets/images/main_menu/new_activity.svg';

  static const String mainMenuNightMode = 'assets/images/main_menu/night_mode.png';

  static const String mainMenuNotify = 'assets/images/main_menu/notify.svg';

  static const String mainMenuObty = 'assets/images/main_menu/obty.svg';

  static const String mainMenuOnlineService  = 'assets/images/main_menu/online_service .svg';

  static const String mainMenuOrder = 'assets/images/main_menu/order.svg';

  static const String mainMenuRecentPlayed = 'assets/images/main_menu/recent_played.svg';

  static const String mainMenuRgdj = 'assets/images/main_menu/rgdj.svg';

  static const String mainMenuSbty = 'assets/images/main_menu/sbty.svg';

  static const String mainMenuSetting = 'assets/images/main_menu/setting.svg';

  static const String mainMenuSport = 'assets/images/main_menu/sport.png';

  static const String mainMenuSportPingbo = 'assets/images/main_menu/sport_pingbo.svg';

  static const String mainMenuSyqp = 'assets/images/main_menu/syqp.svg';

  static const String mainMenuUserGrowth = 'assets/images/main_menu/user_growth.svg';

  static const String mainMenuWallet = 'assets/images/main_menu/wallet.svg';

  static const String mainTabbarTabbarActivity = 'assets/images/main_tabbar/tabbar_activity.svg';

  static const String mainTabbarTabbarCustomer = 'assets/images/main_tabbar/tabbar_customer.svg';

  static const String mainTabbarTabbarMenu = 'assets/images/main_tabbar/tabbar_menu.svg';

  static const String mainTabbarTabbarSearch = 'assets/images/main_tabbar/tabbar_search.svg';

  static const String mainTabbarTabbarWallet = 'assets/images/main_tabbar/tabbar_wallet.svg';

  static const String oauthGoogle = 'assets/images/oauth/google.svg';

  static const String oauthLine = 'assets/images/oauth/line.svg';

  static const String oauthMetaMask = 'assets/images/oauth/metaMask.svg';

  static const String oauthTelegram = 'assets/images/oauth/telegram.svg';

  static const String preferencesAvatar1 = 'assets/images/preferences/avatar_1.png';

  static const String preferencesAvatar2 = 'assets/images/preferences/avatar_2.png';

  static const String preferencesAvatar3 = 'assets/images/preferences/avatar_3.png';

  static const String preferencesAvatar4 = 'assets/images/preferences/avatar_4.png';

  static const String preferencesAvatar5 = 'assets/images/preferences/avatar_5.png';

  static const String preferencesAvatar6 = 'assets/images/preferences/avatar_6.png';

  static const String preferencesCurRight = 'assets/images/preferences/cur_right.svg';

  static const String preferencesNoSelected = 'assets/images/preferences/no_selected.svg';

  static const String preferencesPreference = 'assets/images/preferences/preference.png';

  static const String preferencesProfileCredit = 'assets/images/preferences/profile_credit.png';

  static const String preferencesProfileCurrency = 'assets/images/preferences/profile_currency.png';

  static const String preferencesProfileIcon = 'assets/images/preferences/profile_icon.png';

  static const String preferencesProfileInvisibilityMode = 'assets/images/preferences/profile_invisibility_mode.png';

  static const String preferencesProfileLanguage = 'assets/images/preferences/profile_language.png';

  static const String preferencesProfileNotice = 'assets/images/preferences/profile_notice.png';

  static const String preferencesSelected = 'assets/images/preferences/selected.svg';

  static const String registerBonusHeader = 'assets/images/register/bonus_header.png';

  static const String registerVerificationTipsGoogle = 'assets/images/register/verification_tips_google.png';

  static const String registerVerificationTipsMobile = 'assets/images/register/verification_tips_mobile.png';

  static const String registerVerificationTipsSelected = 'assets/images/register/verification_tips_selected.png';

  static const String splashSplash = 'assets/images/splash/splash.jpeg';

  static const String vipCaRe = 'assets/images/vip/ca_re.png';

  static const String vipChessRe = 'assets/images/vip/chess_re.png';

  static const String vipHeaderBg = 'assets/images/vip/header_bg.png';

  static const String vipRealRe = 'assets/images/vip/real_re.png';

  static const String vipSRe = 'assets/images/vip/s_re.png';

  static const String vipSVipDot0 = 'assets/images/vip/s_vip_dot_0.png';

  static const String vipSVipDot1 = 'assets/images/vip/s_vip_dot_1.png';

  static const String vipSVipDot10 = 'assets/images/vip/s_vip_dot_10.png';

  static const String vipSVipDot2 = 'assets/images/vip/s_vip_dot_2.png';

  static const String vipSVipDot3 = 'assets/images/vip/s_vip_dot_3.png';

  static const String vipSVipDot4 = 'assets/images/vip/s_vip_dot_4.png';

  static const String vipSVipDot5 = 'assets/images/vip/s_vip_dot_5.png';

  static const String vipSVipDot6 = 'assets/images/vip/s_vip_dot_6.png';

  static const String vipSVipDot7 = 'assets/images/vip/s_vip_dot_7.png';

  static const String vipSVipDot8 = 'assets/images/vip/s_vip_dot_8.png';

  static const String vipSVipDot9 = 'assets/images/vip/s_vip_dot_9.png';

  static const String vipSVipDotBg = 'assets/images/vip/s_vip_dot_bg.png';

  static const String vipVip0Card = 'assets/images/vip/vip_0_card.png';

  static const String vipVip1Card = 'assets/images/vip/vip_1_card.png';

  static const String vipVip2Card = 'assets/images/vip/vip_2_card.png';

  static const String vipVip3Card = 'assets/images/vip/vip_3_card.png';

  static const String vipVip4Card = 'assets/images/vip/vip_4_card.png';

  static const String vipVip5Card = 'assets/images/vip/vip_5_card.png';

  static const String vipVip6Card = 'assets/images/vip/vip_6_card.png';

  static const String vipVip7Card = 'assets/images/vip/vip_7_card.png';

  static const String vipVip8Card = 'assets/images/vip/vip_8_card.png';

  static const String vipVip9Card = 'assets/images/vip/vip_9_card.png';

  static const String vipVipBackArrow = 'assets/images/vip/vip_back_arrow.svg';

  static const String vipVipDot0 = 'assets/images/vip/vip_dot_0.png';

  static const String vipVipDot1 = 'assets/images/vip/vip_dot_1.png';

  static const String vipVipDot2 = 'assets/images/vip/vip_dot_2.png';

  static const String vipVipDot3 = 'assets/images/vip/vip_dot_3.png';

  static const String vipVipDot4 = 'assets/images/vip/vip_dot_4.png';

  static const String vipVipDot5 = 'assets/images/vip/vip_dot_5.png';

  static const String vipVipDot6 = 'assets/images/vip/vip_dot_6.png';

  static const String vipVipDot7 = 'assets/images/vip/vip_dot_7.png';

  static const String vipVipDot8 = 'assets/images/vip/vip_dot_8.png';

  static const String vipVipDot9 = 'assets/images/vip/vip_dot_9.png';

  static const String vipVipDotBg = 'assets/images/vip/vip_dot_bg.png';

  static const String vipVipRightHeader = 'assets/images/vip/vip_right_header.png';

  static const String vipVipRightV1 = 'assets/images/vip/vip_right_v1.png';

  static const String vipVipRightV2 = 'assets/images/vip/vip_right_v2.png';

  static const String vipVipRightV3 = 'assets/images/vip/vip_right_v3.png';

  static const String vipVipRightV4 = 'assets/images/vip/vip_right_v4.png';

  static const String vipVipRightV5 = 'assets/images/vip/vip_right_v5.png';

  static const String vipVipRightV6 = 'assets/images/vip/vip_right_v6.png';

  static const String vipVipRightV7 = 'assets/images/vip/vip_right_v7.png';

  static const String vipVipRightV8 = 'assets/images/vip/vip_right_v8.png';

  static const String vipVipRightV9 = 'assets/images/vip/vip_right_v9.png';

  static const String vipVipSCard = 'assets/images/vip/vip_s_card.png';

  static const String en = 'assets/lang/en.json';

  static const String th = 'assets/lang/th.json';

  static const String vi = 'assets/lang/vi.json';

  static const String zh = 'assets/lang/zh.json';
}
