export const allSportList = [
  {
    SportCode: '80001',
    OrderBy: '1',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '81001',
    OrderBy: '2',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '88888',
    OrderBy: '3',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00001',
    OrderBy: '4',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00002',
    OrderBy: '5',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00111',
    OrderBy: '6',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00005',
    OrderBy: '7',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '09000',
    OrderBy: '8',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '09001',
    OrderBy: '9',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00031',
    OrderBy: '10',
    IsShowTeamLogo: false,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00020',
    OrderBy: '11',
    IsShowTeamLogo: false,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00004',
    OrderBy: '12',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00003',
    OrderBy: '13',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00023',
    OrderBy: '14',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00034',
    OrderBy: '15',
    IsShowTeamLogo: false,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00016',
    OrderBy: '16',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00017',
    OrderBy: '17',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00011',
    OrderBy: '18',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00019',
    OrderBy: '19',
    IsShowTeamLogo: false,
    HasAnimation: '1',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00061',
    OrderBy: '20',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00022',
    OrderBy: '21',
    IsShowTeamLogo: false,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00009',
    OrderBy: '22',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00013',
    OrderBy: '23',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00012',
    OrderBy: '24',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00029',
    OrderBy: '25',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00060',
    OrderBy: '26',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00006',
    OrderBy: '27',
    IsShowTeamLogo: true,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00007',
    OrderBy: '28',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00014',
    OrderBy: '29',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00015',
    OrderBy: '30',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '1',
    ThirdPartyEnable: '',
  },
  // 特殊項目先移除
  // {
  //     SportCode: "00018",
  //     OrderBy: "31",
  //     IsShowTeamLogo: false,
  //     HasAnimation: "0",
  //     Status: "1",
  //     ThirdPartyEnable: ""
  // },
  {
    SportCode: '00021',
    OrderBy: '32',
    IsShowTeamLogo: false,
    HasAnimation: '1',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00024',
    OrderBy: '33',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00026',
    OrderBy: '34',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00028',
    OrderBy: '35',
    IsShowTeamLogo: true,
    HasAnimation: '0',
    Status: '1',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00032',
    OrderBy: '36',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00037',
    OrderBy: '37',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00106',
    OrderBy: '38',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00109',
    OrderBy: '39',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00110',
    OrderBy: '40',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '00117',
    OrderBy: '41',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '09101',
    OrderBy: '42',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
  {
    SportCode: '09102',
    OrderBy: '43',
    IsShowTeamLogo: false,
    HasAnimation: '0',
    Status: '0',
    ThirdPartyEnable: '',
  },
];
