import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class BankCardsUtils {
  public BANKS: any = {
    A: [
      { value: '安徽省农村信用社', checked: false },
      { value: '安阳市商业银行', checked: false },
      { value: '鞍山银行', checked: false },
      { value: '安顺市商业银行', checked: false },
      { value: '澳门永亨银行', checked: false },
    ],
    B: [
      { value: '北京银行', checked: false },
      { value: '北京农商', checked: false },
      { value: '平安银行', checked: false },
      { value: '保定市商业银行', checked: false },
      { value: '渤海银行', checked: false },
      { value: '包商银行', checked: false },
      { value: '宝鸡商行', checked: false },
      { value: '本溪市商业银行', checked: false },
    ],
    C: [
      { value: '沧州银行', checked: false },
      { value: '重庆三峡银行', checked: false },
      { value: '承德银行', checked: false },
      { value: '成都银行', checked: false },
      { value: '成都农商银行', checked: false },
      { value: '重庆银行', checked: false },
      { value: '重庆农村商业银行股份有限公司', checked: false },
      { value: '常熟农商银行', checked: false },
      { value: '长治商行', checked: false },
      { value: '长沙银行', checked: false },
      { value: '稠州村镇银行', checked: false },
      { value: '成都商业银行', checked: false },
      { value: '长春发展农商银行', checked: false },
    ],
    D: [
      { value: '东亚银行', checked: false },
      { value: '东莞银行', checked: false },
      { value: '东莞农村商业银行', checked: false },
      { value: '大连银行', checked: false },
      { value: '东营商行', checked: false },
      { value: '大同银行"', checked: false },
      { value: '大新银行', checked: false },
      { value: '德阳银行', checked: false },
      { value: '德州市商业银行', checked: false },
      { value: '大华银行', checked: false },
      { value: '东营银行', checked: false },
    ],
    E: [{ value: '鄂尔多斯银行', checked: false }],
    F: [
      { value: '福建海峡银行', checked: false },
      { value: '福建农信', checked: false },
      { value: '阜新银行股份有限公司', checked: false },
      { value: '法国兴业银行（中国）有限公司', checked: false },
      { value: '抚顺银行', checked: false },
      { value: '富滇银行', checked: false },
      { value: '佛山市顺德区农村信用合作联社', checked: false },
    ],
    G: [
      { value: '工商银行', checked: false },
      { value: '广发银行', checked: false },
      { value: '光大银行', checked: false },
      { value: '贵州省农村信用社联合社', checked: false },
      { value: '广西北部湾银行', checked: false },
      { value: '广东农村信用社', checked: false },
      { value: '广州花都稠州村镇银行', checked: false },
      { value: '桂林银行', checked: false },
      { value: '广州农村商业银行', checked: false },
      { value: '甘肃省农村信用社', checked: false },
      { value: '广西农村信用社联合社', checked: false },
      { value: '贵阳银行', checked: false },
      { value: '广州银行', checked: false },
      { value: '赣州银行', checked: false },
      { value: '广东华兴银行', checked: false },
      { value: '广东南粤银行', checked: false },
      { value: '贵州银行', checked: false },
      { value: '甘肃银行', checked: false },
    ],
    H: [
      { value: '华夏银行', checked: false },
      { value: '韩亚银行', checked: false },
      { value: '湖北银行', checked: false },
      { value: '哈尔滨银行', checked: false },
      { value: '鹤壁银行', checked: false },
      { value: '湖北省农村信用社联合社', key: 'huaxia', checked: false },
      { value: '邯郸银行', checked: false },
      { value: '河北银行', checked: false },
      { value: '河北省农村信用社', checked: false },
      { value: '汉口银行', checked: false },
      { value: '海南农信', checked: false },
      { value: '湖南农信社', checked: false },
      { value: '衡水市商业银行', checked: false },
      { value: '徽商银行', checked: false },
      { value: '杭州银行', checked: false },
      { value: '湖州银行', checked: false },
      { value: '恒生银行', checked: false },
      { value: '恒通村镇银行', checked: false },
      { value: '哈密市商业银行', checked: false },
      { value: '葫芦岛市商业银行', checked: false },
      { value: '花旗银行', checked: false },
      { value: '恒丰银行', checked: false },
      { value: '山西省农村信用社', checked: false },
      { value: '深圳农村商业银行', checked: false },
      { value: '汇丰银行', checked: false },
      { value: '黑龙江省农村信用社联合社', checked: false },
      { value: '河南省农村信用社联合社', checked: false },
      { value: '黄河农村商业银行', checked: false },
      { value: '杭州商业银行', checked: false },
      { value: '华侨银行', checked: false },
      { value: '华融湘江银行', checked: false },
    ],
    J: [
      { value: '建设银行', checked: false },
      { value: '交通银行', checked: false },
      { value: '晋城市商业银行', checked: false },
      { value: '金华银行', checked: false },
      { value: '九江银行', checked: false },
      { value: '吉林银行股份有限公司', checked: false },
      { value: '吉林省农村信用社', checked: false },
      { value: '济宁银行股份有限公司', checked: false },
      { value: '江南农村商业银行', checked: false },
      { value: '晋商银行', checked: false },
      { value: '江苏省农村信用社联合社', checked: false },
      { value: '嘉兴银行', checked: false },
      { value: '江西农信', checked: false },
      { value: '江苏江阴农村商业银行', checked: false },
      { value: '锦州银行', checked: false },
      { value: '晋中市商业银行', checked: false },
      { value: '江苏银行', checked: false },
      { value: '江苏长江商业银行', checked: false },
      { value: '九山东省农村信用社', checked: false },
      { value: '集友银行', checked: false },
      { value: '江西银行', checked: false },
      { value: '景德镇商业银行', checked: false },
      { value: '江苏苏宁银行', checked: false },
    ],
    K: [
      { value: '昆仑银行', checked: false },
      { value: '昆山农村商业银行', checked: false },
      { value: '库尔勒市商业银行', checked: false },
      { value: '可汗银行', checked: false },
    ],
    L: [
      { value: '洛阳银行', checked: false },
      { value: '柳州银行', checked: false },
      { value: '辽宁省农村信用社联合社', checked: false },
      { value: '龙江银行股份有限公司', checked: false },
      { value: '临商银行', checked: false },
      { value: '莱芜市商业银行', checked: false },
      { value: '乐山市商业银行', checked: false },
      { value: '凉山州商业银行', checked: false },
      { value: '漯河商行', checked: false },
      { value: '兰州银行', checked: false },
      { value: '泸州市商业银行', checked: false },
      { value: '莱商银行', checked: false },
      { value: '连云港市商业银行', checked: false },
    ],
    M: [
      { value: '民生银行', checked: false },
      { value: '绵阳市商业银行', checked: false },
      { value: '梅县客家村镇银行', checked: false },
    ],
    N: [
      { value: '农业银行', checked: false },
      { value: '内蒙古银行', checked: false },
      { value: '内蒙古农信社', checked: false },
      { value: '宁波银行', checked: false },
      { value: '南昌银行', checked: false },
      { value: '南充商行', checked: false },
      { value: '南京银行', checked: false },
      { value: '南宁市商业银行', checked: false },
      { value: '宁夏银行', checked: false },
      { value: '宁波鄞州农村合作银行', checked: false },
      { value: '宁波东海银行', checked: false },
      { value: '南洋商业银行', checked: false },
      { value: '南通商业银行', checked: false },
    ],
    P: [
      { value: '浦发银行', checked: false },
      { value: '盘锦市商业银行', checked: false },
      { value: '攀枝花市商业银行', checked: false },
      { value: '平顶山银行', checked: false },
      { value: '平凉市商业银行', checked: false },
    ],
    Q: [
      { value: '秦皇岛市商业银行', checked: false },
      { value: '青海银行', checked: false },
      { value: '青岛银行', checked: false },
      { value: '青海省农村信用社联合社', checked: false },
      { value: '曲靖市商业银行', checked: false },
      { value: '齐鲁银行', checked: false },
      { value: '泉州银行', checked: false },
      { value: '泉厦门银行股份有限公司', checked: false },
      { value: '齐商银行', checked: false },
    ],
    R: [{ value: '日照银行', checked: false }],
    S: [
      { value: '上海银行', checked: false },
      { value: '上海农商', checked: false },
      { value: '陕西省农村信用社联合社', checked: false },
      { value: '商丘商行', checked: false },
      { value: '苏州银行', checked: false },
      { value: '石嘴山银行股份有限公司', checked: false },
      { value: '四川省农村信用合作社', checked: false },
      { value: '深圳发展银行', checked: false },
      { value: '顺德农商', checked: false },
      { value: '三门峡市商业银行', checked: false },
      { value: '遂宁市商业银行', checked: false },
      { value: '深圳福田银座村镇银行', checked: false },
      { value: '商丘银行', checked: false },
      { value: '上饶银行', checked: false },
      { value: '上海农商行', checked: false },
      { value: '绍兴银行', checked: false },
      { value: '山西尧都农村商业银行', checked: false },
      { value: '上海商业银行', checked: false },
      { value: '丝绸之路银行', checked: false },
      { value: '盛京银行', checked: false },
      { value: '三井住友卡公司', checked: false },
    ],
    T: [
      { value: '泰安市商业银行', checked: false },
      { value: '太仓农村商业银行', checked: false },
      { value: '天津滨海农村商业银行', checked: false },
      { value: '天津银行', checked: false },
      { value: '天津农村商业银行', checked: false },
      { value: '唐山市商业银行', checked: false },
      { value: '台州市商业银行', checked: false },
    ],
    W: [
      { value: '乌海银行', checked: false },
      { value: '乌鲁木齐市商业银行', checked: false },
      { value: '潍坊银行', checked: false },
      { value: '威海市商业银行', checked: false },
      { value: '吴江农村商业银行', checked: false },
      { value: '无锡农村商业银行', checked: false },
      { value: '温州银行', checked: false },
      { value: '武汉农村商业银行', checked: false },
      { value: '无锡市商业银行', checked: false },
    ],
    X: [
      { value: '兴业银行', checked: false },
      { value: '新疆汇和银行', checked: false },
      { value: '兴业银行深圳分行', checked: false },
      { value: '新乡市商业银行', checked: false },
      { value: '西藏银行', checked: false },
      { value: '星展银行', checked: false },
      { value: '西安银行', checked: false },
      { value: '新疆银行', checked: false },
      { value: '新韩银行', checked: false },
      { value: '许昌市商业银行', checked: false },
      { value: '邢台银行', checked: false },
      { value: '新疆维吾尔自治区农村信用社联合社', checked: false },
      { value: '信阳银行', checked: false },
    ],
    Y: [
      { value: '邮政储蓄', checked: false },
      { value: '营口市商业银行', checked: false },
      { value: '云南省农村信用社', checked: false },
      { value: '阳泉市商业银行', checked: false },
      { value: '烟台市商业银行', checked: false },
      { value: '玉溪市商业银行', checked: false },
      { value: '雅安市商业银行', checked: false },
      { value: '宜宾市商业银行', checked: false },
      { value: '友利银行', checked: false },
    ],
    Z: [
      { value: '中国银行', checked: false },
      { value: '中信银行', checked: false },
      { value: '中国银联', checked: false },
      { value: '朝阳银行', checked: false },
      { value: '浙江稠州商业银行', checked: false },
      { value: '招商银行', checked: false },
      { value: '珠江村镇银行', checked: false },
      { value: '中银通商务支付有限公司', checked: false },
      { value: '中银富登村镇银行', checked: false },
      { value: '浙江省农村信用社联合社', checked: false },
      { value: '周口市商业银行', checked: false },
      { value: '郑州银行', checked: false },
      { value: '渣打银行', checked: false },
      { value: '浙江泰隆商业银行', checked: false },
      { value: '自贡市商业银行', checked: false },
      { value: '张家口市商业银行', checked: false },
      { value: '浙江民泰商业银行', checked: false },
      { value: '张家港农村商业银行', checked: false },
      { value: '枣庄银行', checked: false },
      { value: '大丰银行', checked: false },
      { value: '长安银行', checked: false },
      { value: '中原银行', checked: false },
      { value: '周中信银行信用卡', checked: false },
      { value: '珠海华润银行', checked: false },
      { value: '浙商银行', checked: false },
      { value: '遵义市商业银行股份有限公司', checked: false },
    ],
  };
}
