import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class StairsService {
  defaultRowStairs = [
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 16 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 17 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 18 },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: false, stone: false, stair: false, disabled: true, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 16 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 16 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 17 },
        { empty: false, stone: false, stair: false, disabled: true, steps: 18 },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 16 },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: false, stone: false, stair: false, disabled: true, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 16 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 17 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 18 },
        { empty: true, stone: false, stair: false, disabled: true },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: true, stone: false, stair: false, disabled: true },
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 16 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 17 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 18 },
      ],
    },
    {
      disabled: true,
      item: [
        { empty: false, stone: false, stair: false, disabled: false, steps: 0 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 1 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 2 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 3 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 4 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 5 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 6 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 7 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 8 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 9 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 10 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 11 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 12 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 13 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 14 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 15 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 16 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 17 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 18 },
        { empty: false, stone: false, stair: false, disabled: false, steps: 19 },
      ],
    },
  ];
}
