import { IncomeSourceForm, RiskFormMap, UploadItem } from 'src/app/shared/interfaces/risk-control.interface';

/** 提升额度数据 */
export const IncomeProofForm: IncomeSourceForm = {
  selectAmount: {
    order: 1,
    drop: true,
    label: 'select_quota_error',
    value: '',
    btmText: 'select_quota_tips',
    optionLists: [
      {
        name: '≥ 500K USD',
        value: 'GreaterOrEqual500K',
      },
      {
        name: '≥ 1M USD',
        value: 'GreaterOrEqual1M',
      },
      {
        name: '≥ 2M USD',
        value: 'GreaterOrEqual2M',
      },
    ],
  },
  foundSource: {
    order: 2,
    customItem: true,
    label: 'wealth_source',
    value: '',
    optionLists: [
      {
        name: 'wealth_source_salary',
        checked: false,
        value: 'salary',
      },
      {
        name: 'wealth_source_sole_trader',
        checked: false,
        value: 'soleTrader',
      },
      {
        name: 'wealth_source_deposits',
        checked: false,
        value: 'deposits',
      },
      {
        name: 'wealth_source_pension',
        checked: false,
        value: 'pension',
      },
      {
        name: 'company_dividends',
        checked: false,
        value: 'stock',
      },
      {
        name: 'aff_c_jy',
        checked: false,
        value: 'business',
      },
      {
        name: 'wealth_source_invest',
        checked: false,
        value: 'invest',
      },
      {
        name: 'wealth_source_gamble_upload_title',
        checked: false,
        value: 'gamble',
      },
      {
        name: 'wealth_source_sale_house',
        checked: false,
        value: 'saleHouse',
      },
      {
        name: 'wealth_source_rent',
        checked: false,
        value: 'rent',
      },
      {
        name: 'wealth_source_borrow_money_upload_title',
        checked: false,
        value: 'borrowMoney',
      },
      {
        name: 'wealth_source_legacy_upload_title',
        checked: false,
        value: 'legacy',
      },
      {
        name: 'wealth_source_contributed_upload_title',
        checked: false,
        value: 'contributed',
      },
      {
        name: 'wealth_source_other_upload_title',
        checked: false,
        value: 'other',
      },
    ],
  },
};

/** 财富来源上传列表 */
export const IncomeUploadList: { [key: string]: UploadItem } = {
  salary: {
    label: 'wealth_source_salary_upload_title',
    order: 3,
    infoLists: 'wealth_source_salary_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'salaryImages',
  },
  soleTrader: {
    label: 'wealth_source_sole_trader_upload_title',
    order: 4,
    infoLists: 'wealth_source_sole_trader_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'soleTraderImages',
  },
  deposits: {
    label: 'wealth_source_deposits_upload_title',
    order: 5,
    infoLists: 'wealth_source_deposits_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'depositsImages',
  },
  pension: {
    label: 'wealth_source_pension_upload_title',
    order: 6,
    infoLists: 'wealth_source_pension_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'pensionImages',
  },
  stock: {
    label: 'wealth_source_stock_upload_title',
    order: 6,
    infoLists: 'wealth_source_stock_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'stockImages',
  },
  business: {
    label: 'wealth_source_business_upload_title',
    order: 7,
    infoLists: 'wealth_source_business_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'businessImages',
  },
  invest: {
    label: 'wealth_source_invest_upload_title',
    order: 8,
    infoLists: 'wealth_source_invest_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'investImages',
  },
  gamble: {
    label: 'wealth_source_gamble_upload_title',
    order: 8,
    infoLists: 'wealth_source_gamble_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'gambleImages',
  },
  saleHouse: {
    label: 'wealth_source_sale_house_upload_title',
    order: 8,
    infoLists: 'wealth_source_sale_house_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'saleHouseImages',
  },
  rent: {
    label: 'wealth_source_rent_upload_title',
    order: 8,
    infoLists: 'wealth_source_rent_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'rentImages',
  },
  borrowMoney: {
    label: 'wealth_source_borrow_money_upload_title',
    order: 8,
    infoLists: 'wealth_source_borrow_money_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'borrowMenoyImages',
  },
  legacy: {
    label: 'wealth_source_legacy_upload_title',
    order: 8,
    infoLists: 'wealth_source_legacy_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'legacyImages',
  },
  contributed: {
    label: 'wealth_source_contributed_upload_title',
    order: 8,
    infoLists: 'wealth_source_contributed_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'contributedImages',
  },
  other: {
    label: 'wealth_source_other_upload_title',

    order: 8,
    infoLists: 'wealth_source_other_upload_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'otherImages',
  },
};

/**提供交易记录截图 */
export const TrxUploadList: { [key: string]: UploadItem } = {
  bankRecord: {
    label: 'bank_card_record',
    order: 3,
    infoLists: 'bank_card_record_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'bankRecordImages',
  },
  cryptoRecord: {
    label: 'crypto_wallet_record',
    order: 3,
    infoLists: 'crypto_wallet_record_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    value: 'cryptoCurrencyRecordImages',
  },
};

export const VideoUpload: { [key: string]: UploadItem } = {
  video: {
    label: 'appeal_announcements',
    order: 3,
    infoLists: 'personal_declaration_video_tips',
    fileList: [],
    loading: false,
    isShowSkeleton: false,
    currentIdx: 0,
    isShowEnlargeImg: false,
    isShowCloseBtn: false,
    isVideo: true,
    value: 'videoUrl',
    videoUrl: '',
    reqLimit: 'file_not_big',
  },
};

export const RISKPAGEMAP: Record<RiskFormMap, { title: string; router: string }> = {
  [RiskFormMap.RISKASSESSMENT]: {
    title: 'risk_assessment_action',
    router: 'edd',
  },
  [RiskFormMap.WEALTHSOURCE]: {
    title: 'wealth_source_certificate_action',
    router: 'proof-of-income',
  },
  [RiskFormMap.FULLAUDIT]: {
    title: 'upload_specified_file',
    router: 'upload-files',
  },
};
